"use strict";

// CallRecoveryLead — one CASE-LEVEL recovery episode, not one dial and not one
// provider contact.
//
// Work order CR-2 (`.ai/context/CALLRAIL_LONG_CALL_RECOVERY_WORK_ORDER_2026-07-31.md`).
//
// This collection answers exactly one question:
//
//   > Why is this case a member of the long-call recovery program, and is that
//   > program still open for consideration?
//
// It is NOT a queue, a scheduler, a counter, an allocator, or a PhoneBurner
// writer. `leadDeliveryService` remains the only decision owner and
// `LeadDeliveryItem` remains the only live delivery store. Everything here is
// upstream evidence — if this collection disappeared, no dial would change
// behaviour, only the reason a case was considered.
//
// WHAT IS DELIBERATELY ABSENT (contract §7.1): raw CallRail payloads, Logics
// responses, recording URLs, transcripts, tokens, secrets, provider bodies. An
// evidence record that accumulates payloads becomes a second copy of the
// customer record, and then it needs its own retention policy, its own redaction
// rules and its own breach surface. Identifiers and verdicts only.

const mongoose = require("mongoose");

const PROGRAM_KEY = "callrail-mail-long-call-v1";

// §6 — the only legal states. `terminal` and `expired` are absorbing.
const STATES = Object.freeze([
  "discovered",
  "awaiting_start",
  "eligible",
  "active",
  "held",
  "review",
  "terminal",
  "expired",
]);

// §6 — legal transitions. Encoded here so the repository can refuse an illegal
// one rather than each caller re-deriving the rule. Absorbing states map to
// themselves ONLY: a terminal episode is never silently reactivated, and a new
// qualifying inquiry after expiry becomes a NEW episode with its own number.
const TRANSITIONS = Object.freeze({
  discovered: Object.freeze(["awaiting_start", "held", "review", "terminal"]),
  awaiting_start: Object.freeze(["eligible", "held", "review", "terminal", "expired"]),
  eligible: Object.freeze(["active", "held", "review", "terminal", "expired"]),
  active: Object.freeze(["eligible", "held", "review", "terminal", "expired"]),
  held: Object.freeze(["eligible", "review", "terminal", "expired"]),
  // review leaves only by explicit reconciliation — never by a background sweep
  // deciding on its own that an ambiguity resolved itself.
  review: Object.freeze(["held", "eligible", "terminal", "expired"]),
  terminal: Object.freeze([]),
  expired: Object.freeze([]),
});

// §7.3 — evidence cap. First/latest timestamps and max duration are kept
// SEPARATELY precisely so that capping the id list can never change business
// state; the cap is an audit convenience, not an input.
const EVIDENCE_CALL_ID_CAP = 25;

const DNC_RESULTS = Object.freeze(["clean", "hit", "failed", "unknown"]);

function nullableTrimmed(value) {
  if (value == null) return null;
  const normalized = String(value).trim();
  return normalized || null;
}

const dncSchema = new mongoose.Schema({
  checkedAt: { type: Date, default: null },
  nextCheckAt: { type: Date, default: null },
  // `unknown` is the honest default: never checked is not the same as clean, and
  // this field is read by an admission gate that must fail closed.
  result: { type: String, enum: DNC_RESULTS, default: "unknown" },
  reason: { type: String, default: null, set: nullableTrimmed, maxlength: 200 },
}, { _id: false });

const humanAnswerEvidenceSchema = new mongoose.Schema({
  // §11 — normalized SAFE identifiers and a verdict. Never a name, never a
  // transcript, never the leg payload.
  status: { type: String, enum: ["proved", "unproven", "rejected"], default: "unproven" },
  reason: { type: String, default: null, set: nullableTrimmed, maxlength: 120 },
  agentId: { type: String, default: null, set: nullableTrimmed, maxlength: 80 },
  extension: { type: String, default: null, set: nullableTrimmed, maxlength: 40 },
  callLogId: { type: String, default: null, set: nullableTrimmed, maxlength: 80 },
}, { _id: false });

const callRecoveryLeadSchema = new mongoose.Schema(
  {
    programKey: { type: String, required: true, default: PROGRAM_KEY, trim: true },
    // Stable opaque episode identity. Generated by the repository from
    // program/domain/case/number so a replayed discovery computes the SAME id
    // rather than minting a second episode.
    episodeId: { type: String, required: true, trim: true },
    episodeNumber: {
      type: Number, required: true, min: 1,
      validate: { validator: Number.isInteger, message: "{PATH} must be an integer" },
    },

    domain: { type: String, required: true, trim: true, uppercase: true },
    // STRING, deliberately. caseId is a string in leaddeliveryitems and an int in
    // profiles/cadences; this repo has been bitten by the mismatch, so the
    // canonical form here is a string and every comparison coerces.
    caseId: { type: String, required: true, trim: true },
    normalizedPhone: { type: String, required: true, trim: true, match: /^\d{10}$/ },
    displayName: { type: String, default: null, set: nullableTrimmed, maxlength: 120 },

    // Immutable once written — the episode's clock (§7.1). expiresAt is derived
    // from it, so letting a later call move it would silently extend the program.
    firstQualifyingCallAt: { type: Date, required: true },
    latestQualifyingCallAt: { type: Date, required: true },
    qualifyingCallIds: { type: [String], default: [] },
    // Pacific dates on which qualifying evidence was observed. Daily cohort
    // manifests reference the episode; this key makes rebuilding one day
    // deterministic without turning the manifest into another customer store.
    qualifyingDateKeys: { type: [String], default: [], match: /^\d{4}-\d{2}-\d{2}$/ },
    maximumObservedDurationSec: {
      type: Number, required: true, min: 0,
      validate: { validator: Number.isInteger, message: "{PATH} must be an integer" },
    },

    mailSourceCanonicalId: { type: String, default: null, set: nullableTrimmed, maxlength: 80 },
    mailSourceName: { type: String, default: null, set: nullableTrimmed, maxlength: 160 },
    humanAnswerEvidence: { type: humanAnswerEvidenceSchema, default: () => ({}) },

    discoveredAt: { type: Date, required: true },
    eligibleFrom: { type: Date, required: true },
    expiresAt: { type: Date, required: true },

    state: { type: String, required: true, enum: STATES, default: "discovered" },
    stateReason: { type: String, default: null, set: nullableTrimmed, maxlength: 200 },
    lastEligibilityCheckedAt: { type: Date, default: null },
    lastStatusCheckedAt: { type: Date, default: null },

    dnc: { type: dncSchema, default: () => ({}) },

    // The one-active-episode invariant is enforced by a PARTIAL unique index on
    // this field (see below), so it is stored as `true` or UNSET — never `false`.
    // A `false` would occupy the index and make the partial filter useless.
    activeEpisode: { type: Boolean, default: undefined },
    linkedLeadDeliveryItemId: { type: mongoose.Schema.Types.ObjectId, default: null },
    supersedesEpisodeId: { type: String, default: null, trim: true },

    // §7.4 — every state mutation is a versioned compare-and-set. Named `version`
    // rather than reusing mongoose's __v because we increment it deliberately on
    // business transitions, not on every save.
    /**
     * Do not re-consider this episode before this instant.
     *
     * Admission re-proves status, sale and DNC on EVERY pass, deliberately — a
     * clean nightly snapshot cannot authorize a call this afternoon. But that
     * only needs to be true at the moment of ADMITTING. A HELD episode is not
     * being called, and re-proving it every 60-second tick meant the held head
     * of the queue was re-read from Logics all day: a live getCaseInfo per
     * episode per tick, admitting nothing, and starving the eligible episodes
     * behind it because the walk never got past them.
     *
     * Stamped when a hold is recorded, cleared by the sweeps that change the
     * inputs a hold depends on. `null` means consider immediately.
     */
    nextConsiderAt: { type: Date, default: null, index: true },

    version: { type: Number, required: true, default: 0, min: 0 },
  },
  { timestamps: true, minimize: false },
);

// §7.2 — indexes.
callRecoveryLeadSchema.index({ episodeId: 1 }, { unique: true });
callRecoveryLeadSchema.index(
  { programKey: 1, domain: 1, caseId: 1, episodeNumber: 1 },
  { unique: true },
);
// ONE active episode per case per program. Partial so that terminal/expired
// history accumulates freely underneath it — the whole point of episodes is
// that a case can re-enter the program later without erasing what happened.
callRecoveryLeadSchema.index(
  { programKey: 1, domain: 1, caseId: 1, activeEpisode: 1 },
  { unique: true, partialFilterExpression: { activeEpisode: true } },
);
callRecoveryLeadSchema.index({ state: 1, eligibleFrom: 1, expiresAt: 1 });
callRecoveryLeadSchema.index({ "dnc.nextCheckAt": 1, state: 1 });
callRecoveryLeadSchema.index({ normalizedPhone: 1, state: 1 });
// Idempotent evidence lookup: "have I already recorded this CallRail id?"
callRecoveryLeadSchema.index({ qualifyingCallIds: 1 });
callRecoveryLeadSchema.index({ programKey: 1, qualifyingDateKeys: 1 });

module.exports =
  mongoose.models.ControlPlaneCallRecoveryLead ||
  mongoose.model("ControlPlaneCallRecoveryLead", callRecoveryLeadSchema);

module.exports.PROGRAM_KEY = PROGRAM_KEY;
module.exports.STATES = STATES;
module.exports.TRANSITIONS = TRANSITIONS;
module.exports.EVIDENCE_CALL_ID_CAP = EVIDENCE_CALL_ID_CAP;
module.exports.DNC_RESULTS = DNC_RESULTS;
