"use strict";

const DEFAULT_MAX_TEXT_CHARS = 6000;
const DEFAULT_MAX_CANDIDATES = 24;

const EXTRA_CONTEXT_ALIASES = Object.freeze({
  legitimacy: [
    "fake call",
    "fraud",
    "fraudulent",
    "spam",
    "spam likely",
    "robo",
    "robocall",
    "telemarketer",
    "is this fake",
    "is this a scam",
    "are you a scam",
    "are you legit",
    "are you legitimate",
    "is this legitimate",
    "where are you calling from",
    "what business is this",
    "what organization",
    "what is your company",
    "what company are you with",
    "who do you work for",
    "what is this regarding",
    "what is this about",
    "why is this number calling me",
    "why do you have my information",
    "how did you get my info",
    "how did you get my information",
    "where did you get my info",
    "where did you get my information",
    "i did not ask for this",
    "i never requested this",
    "i don't remember filling anything out",
    "i dont remember filling anything out",
    "i never filled anything out",
    "i did not fill anything out",
    "i didnt fill anything out",
    "i didn't request a call",
    "i didnt request a call",
    "how do i know this is real",
    "how do i know you are real",
    "prove this is real",
  ],
  irs_notice: [
    "irs",
    "government letter",
    "treasury letter",
    "department of the treasury",
    "notice from treasury",
    "letter from treasury",
    "irs bill",
    "irs balance",
    "irs debt",
    "owe irs",
    "federal balance",
    "federal taxes owed",
    "federal tax debt",
    "past due tax",
    "tax debt",
    "taxes owed",
    "owe taxes",
    "owe back taxes",
    "owe federal",
    "owe federal taxes",
    "owe the government",
    "owe money to the irs",
    "owe the irs",
    "back tax balance",
    "back taxes owed",
    "amount you owe",
    "balance owed",
    "past due amount",
    "amount due immediately",
    "intent to seize",
    "intent to garnish",
    "final demand",
    "urgent tax notice",
    "notice cp",
    "cp notice",
    "cp 501",
    "cp501",
    "cp 503",
    "cp503",
    "cp 504",
    "cp504",
    "cp 2000",
    "cp2000",
    "cp 14",
    "cp14",
    "cp 90",
    "cp90",
    "cp 91",
    "cp91",
    "lt 16",
    "lt16",
    "lt 11",
    "lt11",
    "lt 1058",
    "lt1058",
    "letter eleven",
    "letter ten fifty eight",
    "1058 letter",
    "certified notice",
    "certified mail from irs",
    "letter says i owe",
    "notice says i owe",
    "irs says i owe",
    "tax transcript",
    "account transcript",
    "return transcript",
    "tax year notice",
  ],
  state_tax: [
    "state",
    "state taxes owed",
    "owe the state",
    "owe state taxes",
    "state tax debt",
    "state tax bill",
    "state revenue",
    "state collections department",
    "state tax department",
    "state tax agency",
    "california ftb",
    "ftb notice",
    "ftb balance",
    "franchise tax board",
    "edd notice",
    "edd payroll",
    "employment development department",
    "board of equalization",
    "department of revenue",
    "dept of revenue",
    "dor",
    "department of taxation and finance",
    "taxation and finance",
    "comptroller",
    "tax commission",
    "state withholding",
    "state sales tax",
    "state unemployment",
    "state levy notice",
    "state lien notice",
    "state wage garnishment",
    "state took my refund",
    "state refund offset",
    "new york tax",
    "nys tax",
    "texas comptroller",
    "oklahoma tax commission",
    "illinois department of revenue",
    "georgia department of revenue",
    "arizona department of revenue",
    "oregon department of revenue",
    "washington department of revenue",
  ],
  collection_pressure: [
    "levy",
    "lien",
    "garnish",
    "garnishment",
    "taking money",
    "take money from me",
    "take my money",
    "take my bank",
    "take my bank account",
    "take my wages",
    "take my paycheck",
    "take my check",
    "take my house",
    "take my car",
    "took my refund",
    "took my tax refund",
    "took my money",
    "took money from my account",
    "intercepted my refund",
    "refund offset",
    "offset my refund",
    "put a hold on my account",
    "hold on my account",
    "hold on my wages",
    "hold on my paycheck",
    "they are after me",
    "coming after me",
    "they are threatening me",
    "threatening levy",
    "threatening lien",
    "threatening garnishment",
    "levy my account",
    "levy my bank",
    "levy my bank account",
    "levy my wages",
    "levy my paycheck",
    "levy my check",
    "levied my bank",
    "levied my wages",
    "levied my paycheck",
    "garnish my wages",
    "garnish my check",
    "garnish my pay",
    "garnish my paycheck",
    "garnished my wages",
    "garnished my check",
    "garnished my paycheck",
    "wage attachment",
    "wage withholding order",
    "income withholding order",
    "bank freeze",
    "bank hold",
    "bank account freeze",
    "frozen bank",
    "frozen bank account",
    "account hold",
    "account locked",
    "locked bank account",
    "money taken out",
    "money out of my wages",
    "money out of my paycheck",
    "notice of levy",
    "notice of lien",
    "federal tax lien",
    "tax lien filed",
    "tax warrant",
    "seizure notice",
    "asset levy",
    "property seizure",
    "asset seizure",
    "revenue officer",
    "collections officer",
    "collection agency",
    "private collection agency",
    "they filed a lien",
    "filed a tax lien",
    "intent to levy",
    "final notice of intent",
    "notice of intent to levy",
  ],
  unfiled_returns: [
    "behind on taxes",
    "behind on my taxes",
    "behind filing",
    "behind on filing",
    "missing years",
    "missed years",
    "missed returns",
    "missing returns",
    "not filed for years",
    "not filed taxes",
    "not filed my taxes",
    "not filed a return",
    "not filed returns",
    "not filed since",
    "did not file for years",
    "didn't file for years",
    "didnt file for years",
    "haven't filed for years",
    "havent filed for years",
    "haven't filed taxes",
    "havent filed taxes",
    "haven't filed my taxes",
    "havent filed my taxes",
    "haven't filed since",
    "havent filed since",
    "have not filed since",
    "have not filed taxes",
    "have not filed my taxes",
    "no return filed",
    "never filed",
    "forgot to file",
    "forgot to file taxes",
    "did not submit returns",
    "didn't submit returns",
    "didnt submit returns",
    "back filing",
    "catch up on filing",
    "catch up taxes",
    "catch up returns",
    "old returns",
    "prior year returns",
    "compliance issue",
    "substitute return",
    "substitute for return",
    "sfr",
    "non filer",
    "non-filer",
    "failure to file",
    "late filing",
    "filed late",
    "haven't done my taxes",
    "havent done my taxes",
    "taxes not done",
    "returns not done",
  ],
  payroll_tax: [
    "payroll",
    "payroll taxes",
    "941 tax",
    "941",
    "form 941",
    "940 tax",
    "940",
    "form 940",
    "payroll debt",
    "payroll balance",
    "payroll withholding",
    "withheld taxes",
    "employment taxes owed",
    "business payroll problem",
    "business payroll taxes",
    "trust fund penalty",
    "responsible person penalty",
    "tfrp penalty",
    "employee tax deposits",
    "payroll deposits",
    "failed payroll deposits",
    "missed payroll deposits",
    "quarterly 941",
    "irs business account",
    "business is still operating",
    "shut down the business",
    "closed the business",
    "business closed",
    "business shut down",
    "trust fund",
    "trust fund recovery",
    "responsible person",
    "responsible officer",
    "employees",
    "employee withholding",
    "withheld from employees",
    "941 quarters",
    "payroll quarters",
    "federal tax deposits",
    "eftps",
    "missed deposits",
    "payroll penalties",
    "business tax debt",
    "business owes the irs",
  ],
  self_employment: [
    "gig income",
    "app income",
    "rideshare",
    "ride share",
    "delivery driver",
    "delivery income",
    "doordash",
    "door dash",
    "uber",
    "lyft",
    "instacart",
    "grubhub",
    "shipt",
    "contract work",
    "contract labor",
    "independent contractor",
    "contractor",
    "freelance",
    "freelancer",
    "cash jobs",
    "cash business",
    "cash income",
    "under the table",
    "side business",
    "side hustle",
    "sole proprietor",
    "sole prop",
    "llc income",
    "schedule c",
    "1099 income",
    "ten ninety nine",
    "ten ninety nine k",
    "ten ninety nine nec",
    "1099k",
    "1099-k",
    "1099 nec",
    "1099-nec",
    "1099 misc",
    "1099-misc",
    "platform income",
    "platform payments",
    "paid through a platform",
    "paid on a platform",
    "payment processor",
    "third party payments",
    "paypal",
    "venmo",
    "cash app",
    "cashapp",
    "zelle",
    "etsy",
    "ebay",
    "shopify",
    "stripe",
    "square",
    "did not pay estimated",
    "didn't pay estimated",
    "didnt pay estimated",
    "estimated payments",
    "quarterly payments",
    "no taxes taken out",
    "taxes not taken out",
    "no withholding",
    "write off",
    "write offs",
    "business expenses",
    "mileage",
  ],
  audit_adjustment: [
    "they changed what i owe",
    "they changed my taxes",
    "they changed my return",
    "irs changed my return",
    "irs changed what i owe",
    "computer notice",
    "matching notice",
    "matching program",
    "automated underreporter",
    "underreporter",
    "income they say i missed",
    "missed income",
    "income mismatch",
    "1099 mismatch",
    "w2 mismatch",
    "w-2 mismatch",
    "reported income",
    "income reported to them",
    "under reported",
    "underreported",
    "disallowed expense",
    "disallowed credit",
    "disallowed deduction",
    "denied deduction",
    "denied credit",
    "prove expenses",
    "prove deductions",
    "show receipts",
    "need receipts",
    "audit",
    "audited",
    "being audited",
    "exam",
    "examination",
    "audit reconsideration",
    "notice of deficiency",
    "statutory notice",
    "ninety-day letter",
    "90-day letter",
    "tax court",
    "petition tax court",
    "proposed assessment",
    "proposed changes",
    "audit letter",
    "audit appointment",
  ],
  spouse_identity: [
    "old spouse",
    "former spouse",
    "ex filed",
    "ex wife filed",
    "ex husband filed",
    "my spouse filed",
    "spouse owes",
    "spouse debt",
    "joint return problem",
    "joint tax debt",
    "joint liability",
    "married filing jointly",
    "married filing joint",
    "innocent spouse relief",
    "injured spouse relief",
    "stolen social",
    "stolen ssn",
    "stolen social security",
    "someone used my social",
    "someone used my ssn",
    "someone filed under my name",
    "someone filed with my social",
    "identity issue",
    "id theft",
    "identity theft",
    "fraudulent return",
    "not my return",
    "not my income",
    "not my tax debt",
    "refund was offset",
    "refund offset for spouse",
    "ex took refund",
    "divorce decree",
    "separated",
    "separation",
    "my ex",
  ],
  money_pressure: [
    "owe",
    "owe money",
    "owe taxes",
    "owe the irs",
    "irs debt",
    "tax debt",
    "back taxes",
    "pay this off",
    "pay it off",
    "pay the irs",
    "pay my taxes",
    "can't pay the irs",
    "cant pay the irs",
    "cannot pay the irs",
    "can't pay taxes",
    "cant pay taxes",
    "cannot pay taxes",
    "can't pay this",
    "cant pay this",
    "cannot pay this",
    "can't afford this",
    "cant afford this",
    "can't make rent",
    "cant make rent",
    "can't pay rent",
    "cant pay rent",
    "behind on rent",
    "behind on mortgage",
    "mortgage payment",
    "rent payment",
    "car note",
    "car payment",
    "car got repo",
    "repossession",
    "living paycheck to paycheck",
    "paycheck to paycheck",
    "fixed income",
    "disability",
    "ssi",
    "ssdi",
    "social security check",
    "social security",
    "retirement check",
    "retired",
    "unemployed",
    "job loss",
    "lost work",
    "lost my job",
    "laid off",
    "hours reduced",
    "hours cut",
    "medical debt",
    "medical expenses",
    "hospital bill",
    "hospital bills",
    "doctor bills",
    "medicine",
    "prescriptions",
    "child expenses",
    "kids to feed",
    "single parent",
    "child support",
    "daycare",
    "school expenses",
    "need my paycheck",
    "need my bank account",
    "cannot afford",
    "barely getting by",
    "barely making it",
    "broke",
    "no money",
    "low income",
    "income went down",
    "business is slow",
    "cash flow",
    "business cash flow",
    "can't keep up",
    "cant keep up",
    "falling behind",
    "behind on bills",
    "utilities",
    "electric bill",
    "gas bill",
    "groceries",
    "food",
  ],
  emotional_pressure: [
    "irs debt",
    "tax debt",
    "owe the irs",
    "tax bill scares me",
    "scared of the irs",
    "worried about the irs",
    "afraid of the irs",
    "terrified of the irs",
    "nervous about the irs",
    "freaked out",
    "freaking out",
    "losing sleep",
    "keeping me up",
    "can't sleep",
    "cant sleep",
    "sleepless",
    "don't know what to do",
    "dont know what to do",
    "don't know where to start",
    "dont know where to start",
    "no idea what to do",
    "no clue what to do",
    "don't understand this",
    "dont understand this",
    "i don't understand",
    "i dont understand",
    "i feel stuck",
    "stuck",
    "this is too much",
    "i'm overwhelmed",
    "im overwhelmed",
    "overwhelmed",
    "i'm scared",
    "im scared",
    "scared",
    "afraid",
    "terrified",
    "i'm worried",
    "im worried",
    "worried",
    "i'm stressed",
    "im stressed",
    "stressed",
    "stressful",
    "panic",
    "panicking",
    "anxiety",
    "anxious",
    "i feel embarrassed",
    "i feel ashamed",
    "this is embarrassing",
    "embarrassed",
    "ashamed",
    "humiliated",
    "my fault",
    "i messed up",
    "this is stressful",
    "i'm pissed",
    "im pissed",
    "pissed off",
    "angry",
    "mad",
    "frustrated",
    "this is ridiculous",
    "they are harassing me",
    "they keep calling",
  ],
  objection: [
    "i don't want to talk",
    "i dont want to talk",
    "do not want to talk",
    "don't want to deal with this",
    "dont want to deal with this",
    "not a good time",
    "now is not good",
    "i'm at work",
    "im at work",
    "at work",
    "in a meeting",
    "driving",
    "can't talk",
    "cant talk",
    "cannot talk",
    "call later",
    "call another time",
    "call me later",
    "call me tomorrow",
    "call me back",
    "try me later",
    "send information",
    "send me information",
    "text me",
    "just text me",
    "email information",
    "email me",
    "mail information",
    "mail me something",
    "send it in writing",
    "send me something",
    "let me think",
    "need to think",
    "think about it",
    "sleep on it",
    "talk to my spouse",
    "ask my spouse",
    "talk to my wife",
    "talk to my husband",
    "ask my wife",
    "ask my husband",
    "talk to my accountant",
    "talk to my cpa",
    "talk to my tax person",
    "my accountant handles it",
    "my cpa handles it",
    "my tax guy handles it",
    "already working with someone",
    "already paid someone",
    "already have someone",
    "already have a lawyer",
    "already have an attorney",
    "already have a cpa",
    "have a lawyer",
    "have an attorney",
    "have a cpa",
    "taken care of",
    "handled already",
    "i'll handle it myself",
    "ill handle it myself",
    "i can do it myself",
    "i will do it myself",
    "not interested",
    "remove me",
    "take me off",
    "stop calling",
    "don't call",
    "dont call",
    "do not call",
    "wrong number",
    "you have the wrong number",
    "not my problem",
    "i don't owe",
    "i dont owe",
    "i paid that",
    "already paid",
    "too expensive",
    "can't afford you",
    "cant afford you",
  ],
  representation: [
    "represent",
    "representation",
    "you talk to them for me",
    "talk to them for me",
    "speak with them for me",
    "speak to them for me",
    "call them for me",
    "can you call the irs",
    "can you call them",
    "can you deal with them",
    "can you negotiate",
    "negotiate with them",
    "negotiate the balance",
    "settle with them",
    "settle this",
    "settlement",
    "offer in compromise",
    "oic",
    "payment plan with irs",
    "installment agreement",
    "get my transcripts",
    "access my transcripts",
    "pull my transcripts",
    "pull transcripts",
    "authorization to pull",
    "sign a poa",
    "sign power of attorney",
    "power of attorney",
    "poa",
    "form 2848",
    "form 8821",
    "tax information authorization",
    "take this off my plate",
    "take it off my plate",
    "handle the agency",
    "be my representative",
    "on my behalf",
    "talk to the agency",
    "deal with the agency",
    "talk to revenue officer",
    "call revenue officer",
    "stop them from calling me",
    "make them call you",
    "can you help me with this",
    "what can you do for me",
    "how can you help",
  ],
  fees_close: [
    "owe money",
    "can't pay the irs",
    "cant pay the irs",
    "cannot pay the irs",
    "can't pay taxes",
    "cant pay taxes",
    "cannot pay taxes",
    "can't afford",
    "cant afford",
    "cannot afford",
    "what's the price",
    "whats the price",
    "what's your fee",
    "whats your fee",
    "what are your fees",
    "what would it cost",
    "what does it cost",
    "what do you charge",
    "how much do you charge",
    "how much is this",
    "how much is it",
    "how much money",
    "how much do i need",
    "how much down",
    "down payment",
    "deposit",
    "retainer",
    "retainer fee",
    "monthly payment",
    "payment plan with you",
    "payments with you",
    "make payments to you",
    "can i finance",
    "can i make payments",
    "do you finance",
    "financing",
    "credit card",
    "debit card",
    "ach",
    "checking account",
    "routing number",
    "pay today",
    "start today",
    "start now",
    "sign today",
    "enroll",
    "enrollment",
    "how do i start",
    "how do we start",
    "what's next",
    "whats next",
    "next step",
    "next steps",
    "what do i sign",
    "send the agreement",
    "retainer agreement",
    "engagement agreement",
    "onboarding",
    "move forward",
    "let's do it",
    "lets do it",
    "sign me up",
    "get started",
    "too much",
    "expensive",
    "cheaper",
    "discount",
    "worth it",
  ],
});

const WEAK_CONTEXT_HITS = new Set([
  "irs",
  "notice",
  "letter",
  "taxes",
  "tax debt",
  "debt",
  "balance",
  "state",
  "federal",
  "company",
  "paycheck",
  "my check",
  "bank account",
  "refund",
  "spouse",
  "wife",
  "husband",
  "ex",
  "payment",
  "pay",
  "card",
  "today",
  "sign",
  "paperwork",
  "agreement",
  "contract",
  "cost",
  "price",
  "fee",
  "fees",
  "afford",
  "expensive",
  "business",
  "employees",
  "quarterly",
  "audit",
  "proof",
  "receipts",
  "1099",
  "contractor",
  "state tax",
  "talk to them",
  "handle this",
  "contact them",
  "owe",
  "owe money",
]);

const NEVER_MATCH_KEYWORDS = new Set([
  "a",
  "an",
  "and",
  "are",
  "but",
  "for",
  "i",
  "i'm",
  "im",
  "is",
  "it",
  "me",
  "my",
  "of",
  "or",
  "so",
  "that",
  "the",
  "this",
  "to",
  "uh",
  "um",
  "you",
]);

function cleanText(value, maxLength = 4000) {
  return String(value || "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, maxLength);
}

function normalizeBankText(value, maxLength = DEFAULT_MAX_TEXT_CHARS) {
  return cleanText(value, maxLength)
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/[._/]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function uniqueStrings(values, maxLength = 160) {
  return [...new Set((Array.isArray(values) ? values : [])
    .map((value) => cleanText(value, maxLength))
    .filter(Boolean))];
}

function escapedRegex(value) {
  return String(value || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function keywordHit(normalizedText, keyword) {
  const needle = normalizeBankText(keyword, 240);
  if (!needle) return false;
  if (/^[a-z0-9]+(?:-[a-z0-9]+)?$/i.test(needle)) {
    return new RegExp(`(^|[^a-z0-9])${escapedRegex(needle)}($|[^a-z0-9])`, "i").test(normalizedText);
  }
  const phrasePattern = escapedRegex(needle).replace(/\\\s+/g, "\\s+");
  return new RegExp(`(^|[^a-z0-9])${phrasePattern}($|[^a-z0-9])`, "i").test(normalizedText);
}

function isWeakContextHit(keyword) {
  return WEAK_CONTEXT_HITS.has(normalizeBankText(keyword, 160));
}

function isNeverMatchKeyword(keyword) {
  return NEVER_MATCH_KEYWORDS.has(normalizeBankText(keyword, 160));
}

function makeMatchFragment(text, hit, radius = 42) {
  const source = cleanText(text, DEFAULT_MAX_TEXT_CHARS);
  const lower = source.toLowerCase();
  const needle = String(hit || "").toLowerCase();
  const idx = needle ? lower.indexOf(needle) : -1;
  if (idx < 0) return source.slice(0, Math.min(source.length, 140));
  const start = Math.max(0, idx - radius);
  const end = Math.min(source.length, idx + needle.length + radius);
  return source.slice(start, end).trim();
}

function expandRuleKeywords(rule = {}) {
  const aliases = EXTRA_CONTEXT_ALIASES[rule.key] || [];
  return uniqueStrings([...(rule.keywords || []), ...aliases], 120)
    .filter((keyword) => !isNeverMatchKeyword(keyword));
}

function buildContextRuleCatalog(rules = []) {
  return (Array.isArray(rules) ? rules : [])
    .map((rule) => ({
      key: cleanText(rule.key, 120),
      label: cleanText(rule.label, 120),
      family: cleanText(rule.family, 80),
      priority: Number(rule.priority || 0),
      keywords: expandRuleKeywords(rule).slice(0, 80),
      summary: cleanText(rule.guidance || rule.summary || "", 300),
    }))
    .filter((rule) => rule.key);
}

function findContextCandidateMatches(text, rules = [], options = {}) {
  const limit = Math.max(1, Number(options.limit || DEFAULT_MAX_CANDIDATES));
  const normalizedText = normalizeBankText(text);
  return (Array.isArray(rules) ? rules : [])
    .map((rule) => {
      const allKeywords = expandRuleKeywords(rule);
      const hits = uniqueStrings(allKeywords.filter((keyword) => keywordHit(normalizedText, keyword)), 120);
      if (!hits.length) return null;
      const strongHits = hits.filter((hit) => !isWeakContextHit(hit));
      const score =
        Number(rule.priority || 0) +
        hits.length * 8 +
        strongHits.length * 10 +
        Math.min(12, Math.max(0, 8 - hits[0].length / 10));
      return {
        key: cleanText(rule.key, 120),
        label: cleanText(rule.label || rule.key, 120),
        family: cleanText(rule.family || "sales", 80),
        priority: Number(rule.priority || 0),
        score: Number(score.toFixed(2)),
        hits,
        fragment: makeMatchFragment(text, hits[0]),
        guidance: cleanText(rule.guidance || rule.summary || "", 300),
        summary: cleanText(rule.guidance || rule.summary || "", 300),
      };
    })
    .filter(Boolean)
    .sort((a, b) => b.score - a.score || b.priority - a.priority || b.hits.length - a.hits.length || a.key.localeCompare(b.key))
    .slice(0, limit);
}

function normalizeContextCandidate(candidate = {}) {
  const key = cleanText(candidate.key || "", 80);
  if (!key) return null;
  return {
    key,
    label: cleanText(candidate.label || key, 120),
    family: cleanText(candidate.family || "sales", 80),
    priority: Number(candidate.priority || candidate.score || 0) || 0,
    score: Number(candidate.score || candidate.priority || 0) || 0,
    hits: Array.isArray(candidate.hits)
      ? candidate.hits.map((hit) => cleanText(hit, 120)).filter(Boolean)
      : [],
    fragment: cleanText(candidate.fragment || "", 240),
    guidance: cleanText(candidate.guidance || candidate.summary || "", 300),
    summary: cleanText(candidate.summary || candidate.guidance || "", 300),
  };
}

function normalizeContextCandidates(candidates = [], options = {}) {
  const limit = Math.max(1, Number(options.limit || DEFAULT_MAX_CANDIDATES));
  const byKey = new Map();
  for (const candidate of Array.isArray(candidates) ? candidates : []) {
    const normalized = normalizeContextCandidate(candidate);
    if (!normalized) continue;
    const current = byKey.get(normalized.key);
    if (!current) {
      byKey.set(normalized.key, normalized);
      continue;
    }
    current.priority = Math.max(current.priority, normalized.priority);
    current.score = Math.max(current.score, normalized.score);
    current.hits = uniqueStrings([...current.hits, ...normalized.hits], 120);
    if (!current.fragment && normalized.fragment) current.fragment = normalized.fragment;
    if (!current.guidance && normalized.guidance) current.guidance = normalized.guidance;
    if (!current.summary && normalized.summary) current.summary = normalized.summary;
    if (!current.label && normalized.label) current.label = normalized.label;
    if (!current.family && normalized.family) current.family = normalized.family;
  }
  return [...byKey.values()]
    .sort((a, b) => b.score - a.score || b.priority - a.priority || b.hits.length - a.hits.length || a.key.localeCompare(b.key))
    .slice(0, limit);
}

function mergeContextCandidates(existing = [], incoming = [], options = {}) {
  return normalizeContextCandidates([...(Array.isArray(existing) ? existing : []), ...(Array.isArray(incoming) ? incoming : [])], options);
}

module.exports = {
  EXTRA_CONTEXT_ALIASES,
  NEVER_MATCH_KEYWORDS,
  WEAK_CONTEXT_HITS,
  buildContextRuleCatalog,
  cleanText,
  findContextCandidateMatches,
  isWeakContextHit,
  isNeverMatchKeyword,
  makeMatchFragment,
  mergeContextCandidates,
  normalizeBankText,
  normalizeContextCandidates,
  uniqueStrings,
};
