// Field Manual — Part 2: objections, sections "capability" and "debt".
// Synthesized from the live-coach objection bank (liveCoachObjectionBank.js)
// and the trainer-prompt objection taxonomy. The through-line of this family:
// HONESTY IS THE PLAY. Several of these entries teach the agent to concede
// when the prospect genuinely doesn't need us — because that credibility is
// what closes everyone else.

import type { ManualEntry } from "./types";

export const OBJECTION_CAPABILITY_ENTRIES: ManualEntry[] = [
  // ── capability ────────────────────────────────────────────────────────────
  {
    id: "obj.already-have-cpa",
    part: "objections",
    section: "capability",
    title: "“I already have a CPA / someone does my taxes”",
    aliases: [
      "my cpa",
      "my accountant",
      "have an accountant",
      "accountant handles it",
      "my lawyer",
      "have an attorney",
      "my tax guy",
      "my tax lady",
      "tax preparer handles it",
      "someone does my taxes",
      "i have someone for that",
    ],
    lead: "They think filing and fixing are the same job. They are not — a preparer files returns; collection representation negotiates the debt that already exists. Never disparage the preparer: affirm them, distinguish the work, and offer to work alongside.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "This is comfortable delegation talking, plus a little loyalty. The prospect likes their tax person, doesn’t want to seem disloyal, and — most importantly — genuinely does not know there is a difference between filing taxes and resolving a tax debt. Here’s the tell that the current setup isn’t covering it: the notices are still coming, and they made an inquiry. If the CPA had this handled, you wouldn’t be on the phone. The reframe is not “your guy is bad” — it’s that these are two different licenses doing two different jobs. Filing is [[tax.representation]] on the preparation side; what we do is the collections side: power of attorney, transcripts, negotiating the balance that already exists. Their CPA can keep the returns. We take the fight.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Affirm the preparer first — “good, keep them” — before you distinguish anything. The moment you attack their tax person, you attack their judgment for choosing them, and the wall goes up.",
          "Draw the line between the two jobs in one plain sentence: filing returns versus negotiating an existing debt with the IRS. Different specialty, different license, different work.",
          "Run a gentle value audit: has the CPA filed a power of attorney with the IRS? Pulled collection transcripts? Talked to anyone about the balance? Questions about the work expose the gap without a single insult.",
          "Offer the alongside play: “we work with your CPA all the time — they handle the returns, we handle the collections side.” Cooperation removes the loyalty objection entirely.",
          "Advance to the transcript pull. Whatever the CPA has or hasn’t done, the next step is the same: see what the IRS file actually shows.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "Keep your CPA for the returns — this is the collections side, different license. Let’s pull your transcripts and see where your file actually stands.",
          "Honest question — not a knock on them: has your accountant filed a power of attorney with the IRS on this balance? Because if not, nobody’s actually standing between you and collections.",
          "Good CPAs are worth keeping, and most of them will tell you themselves — negotiating back debt isn’t their lane. We work alongside preparers all the time.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Never disparage the current preparer — “they can’t help you with this” lands as an attack on the prospect’s judgment, not on the CPA.",
          "Don’t lecture about licenses for two minutes. One clean sentence on the difference, then a question.",
          "Don’t force a choice between you and the CPA. The alongside frame wins; the either/or frame loses.",
        ],
      },
      {
        kind: "example",
        weak: "“Your CPA can’t handle this — they don’t know collections. You need us, not them.”",
        strong: "“Keep them — seriously, good preparers are hard to find. But quick question: have they filed a power of attorney on this balance, or pulled your IRS transcripts? That’s the collections side, and it’s a different job than filing. We do that part, and we do it with your CPA, not instead of them.”",
        note: "The strong version affirms the preparer, names the specific missing work (POA, transcripts), and dissolves the loyalty problem by offering to cooperate. Nothing to defend means nothing to argue.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “My accountant’s handled my taxes for fifteen years — I’m not going behind his back.” What’s your move?",
        answer: "Affirm the loyalty out loud — fifteen years means he’s good, keep him. Then distinguish: filing returns and negotiating an existing IRS debt are different jobs with different licenses, and most preparers will say so themselves. Ask whether he’s filed a POA or pulled collection transcripts on the balance. Offer to work alongside him, and advance to the transcript pull.",
      },
    ],
    links: [
      "tax.representation",
      "strat.value-audit",
      "strat.agree-first",
      "script.discovery",
      "obj.hired-another-company",
      "obj.just-file-returns",
    ],
  },
  {
    id: "obj.working-with-irs",
    part: "objections",
    section: "capability",
    title: "“I’m already working directly with the IRS — why would I change?”",
    aliases: [
      "working with the irs",
      "dealing with the irs myself",
      "already talking to the irs",
      "i have an agent at the irs",
      "the irs and i worked something out",
      "i'm handling it with them directly",
    ],
    lead: "Either they truly have it handled, or they’re getting steamrolled and don’t know it. You can’t tell from the objection — only from diagnostic questions. And if the answers say they really have it under control, say so. That honesty is the whole play.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "Two very different prospects say this sentence. The first actually negotiated something reasonable and is fine. The second called the IRS alone, agreed to whatever the collections agent proposed, filed no appeal, and thinks “I have a person there” means representation. It doesn’t — the person there works for the IRS. Your job is not to argue that the IRS is the enemy; it’s to diagnose which prospect you have. Ask what stage the case is at, whether a revenue officer is assigned, and what the current arrangement actually is. Real gaps show up fast: no representation on file, no Collection Due Process appeal, an installment payment set higher than they qualify for. If the gaps are there, name them plainly. If they aren’t — if this person genuinely has it handled — tell them to keep doing what they’re doing. Every honest concession like that is banked credibility, and it’s what makes the next thing you say believable.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Ask the stage question first: “where does it stand — notices, a revenue officer, an installment agreement?” The answer tells you which conversation this is.",
          "Ask who they’re dealing with. “A guy at the IRS” who works in collections is not their advocate — everything said on that line is on the record and works for the government’s side.",
          "Probe the arrangement math: what are they paying, and did anyone check what they actually qualified for? The IRS accepts what you agree to, not what you qualify for — see [[tax.resolution-options]].",
          "Name real gaps honestly and specifically: no POA on file, no appeal rights exercised, a payment that doesn’t survive a bad month.",
          "If the answers check out — say so. “If it’s truly working, keep it” costs you nothing and buys you everything. Then leave the door open: transcripts would confirm it.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "That might be fine — depends what you set up. What are you paying a month, and did anyone check what you actually qualified for before you agreed to it?",
          "Quick thing to know: the agent you’re talking to at the IRS works for the IRS. That’s not a knock on them — it’s just not the same as someone on your side of the table.",
          "Honestly? If you’ve got a fair arrangement and it’s working, keep it. Ten minutes with your transcripts tells us which one you have. If it checks out, I’ll tell you so.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Don’t fear-monger or paint the IRS as a villain — “the IRS is the enemy” makes you sound like the ads that burned everyone.",
          "Don’t assume they’re being steamrolled. Diagnose first; some people really do have it handled.",
          "Don’t argue with a working arrangement you haven’t seen. Argue nothing — ask for the facts, then tell the truth about them.",
        ],
      },
      {
        kind: "example",
        weak: "“Never deal with the IRS yourself — they’re not on your side and they’ll bury you. You need representation, period.”",
        strong: "“Could be you’ve got it handled — some people do. Where does it stand? Is there a revenue officer, or just notices? And the payment you agreed to — did anyone run the numbers on what you qualified for, or did you take what they offered? If it’s solid, I’ll be the first to tell you to keep it.”",
        note: "The weak version is fear-based and generic. The strong version diagnoses with specific stage questions and puts honesty on the table up front — which is exactly what makes the gaps, if they exist, land as fact instead of pitch.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “I’ve got a payment plan going with the IRS already — I set it up myself last year.” What’s your move?",
        answer: "Run the treadmill test: is the balance lower today than the day it was set up? Then ask whether anyone screened them for penalty abatement or hardship status before they agreed — the IRS takes what you offer and doesn’t mention the cheaper doors. If their answers are solid, say so honestly. Either way, the transcripts grade the plan — advance to the pull.",
      },
    ],
    links: [
      "tax.resolution-options",
      "tax.representation",
      "obj.already-on-plan",
      "strat.value-audit",
      "strat.expert-specificity",
      "script.discovery",
    ],
  },
  {
    id: "obj.hired-another-company",
    part: "objections",
    section: "capability",
    title: "“I already hired another company — why would I change?”",
    aliases: [
      "already working with a company",
      "another company is handling it",
      "signed up with another company",
      "already with a tax company",
      "someone is already handling it",
      "already have representation",
      "working with another firm",
      "already hired someone",
      "optima",
      "tax defense network",
      "community tax",
      "anthem tax",
    ],
    lead: "Sometimes a genuine engagement, often quiet buyer’s remorse they haven’t admitted yet — months in, thousands paid, nothing visible happening. Don’t trash-talk the incumbent. Audit the work: was the POA filed? Were transcripts pulled? The answers do the selling.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "Two sub-cases live under this sentence. The first: a firm doing real work — POA on file, transcripts pulled, a case manager they can name. The second, and far more common with the national mills: they paid thousands months ago and can’t tell you the last thing that firm actually did. That’s buyer’s remorse that hasn’t been said out loud yet, and your job is to let them discover it themselves. You do that with an audit, not an attack. “They’re scammers” — when you don’t know — makes you the aggressor and them the defender of their own purchase. Questions about progress trigger no defensiveness at all: what did you pay, what’s the last thing they did, was the POA filed, were transcripts pulled? And the honesty clause is non-negotiable: if the answers show a firm doing real work, say so, and offer to be a resource if things change. That concession is what makes your audit credible for the prospect whose firm has been silent since the deposit cleared.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Ask how it’s going before anything else — tone of the answer tells you which sub-case you have.",
          "Run the value audit, not an attack: “what did you pay, and what’s the last thing they actually did on your file?” If they have to think about it, that usually IS the answer — let them arrive there.",
          "Ask the two verifiable questions: was a power of attorney filed with the IRS? Were your transcripts pulled? These are yes/no facts, not opinions, and most stalled clients answer “I don’t know” — which says everything.",
          "Name the standard they should be getting anywhere: POA filed week one, transcripts pulled, a named case manager, a plan they can repeat back. Not our pitch — the industry’s baseline.",
          "OIC reality check where it applies: if the incumbent filed or promised an Offer in Compromise with no real financial workup, it is not getting approved — say it plainly. Naming the industry’s signature false-hope move builds instant credibility.",
          "If the other firm is genuinely performing: say so, wish them well, and offer to be a resource if things change. Then leave clean.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "Fair question for them, not for me: what did you pay, and what’s the last thing they did on your file? If you have to think about it, that’s the answer.",
          "Here’s what those dollars should be buying anywhere: POA on file week one, transcripts pulled, a named case manager, and a plan you can repeat back. You should have all four. Do you?",
          "If they filed an offer in compromise without doing a full financial workup, I’ll tell you right now — the IRS is going to reject it. That’s not pessimism, that’s how OICs work.",
          "And look — if they’re actually doing the work, stay with them. I mean that. Keep my number in case that changes.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Never call the other firm scammers when you don’t know — trash-talk without facts makes you the one who sounds like a scammer.",
          "Don’t push a hard switch. The pushy-switch play confirms every fear this industry has earned.",
          "Don’t argue with a firm that’s performing. Concede it, bank the credibility, leave the door open.",
        ],
      },
      {
        kind: "example",
        weak: "“Those big national companies are all scams — they took your money and they’re doing nothing. Cancel with them and sign with us today.”",
        strong: "“Might be a good firm — some are. Two quick questions will tell you: did they file the power of attorney with the IRS, and did they pull your transcripts? Those are the first two things any real firm does in week one. If you don’t know the answer, that’s worth finding out before another payment goes through.”",
        note: "The weak version attacks blind and demands a switch. The strong version hands the prospect two verifiable facts to check — and lets the incumbent’s own silence make the case.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “I signed with a big tax-relief company six months ago. They said they’re working on an offer in compromise.” What’s your move?",
        answer: "Audit, don’t attack: what have they actually done — POA filed? Transcripts pulled? Then the honest OIC check: did anyone do a full financial workup before promising that offer? If not, it’s heading for rejection, and paying to wait on a rejection isn’t representation. If they can’t name any completed work in six months, offer to pull transcripts and see what’s really been done on the file.",
      },
    ],
    links: [
      "strat.value-audit",
      "tax.representation",
      "tax.resolution-options",
      "obj.already-have-cpa",
      "obj.burned-before",
      "strat.earn-trust-with-proof",
    ],
  },
  {
    id: "obj.burned-before",
    part: "objections",
    section: "capability",
    title: "“I paid a company like yours before and got burned”",
    aliases: [
      "already paid someone",
      "paid another company",
      "got burned",
      "last company took my money",
      "they did nothing",
      "tried this before",
      "went through this already",
      "previous firm ripped me off",
      "lost money on this before",
    ],
    lead: "One of the hardest trust states on the phone: they did the right thing once and got robbed — and often there’s shame riding under the anger. Ask what happened, listen longer than feels efficient, then differentiate with process, not adjectives. You inherit the last firm’s burden of proof.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "This is a pain point, not a brush-off. The prospect reached for help when they were vulnerable, paid real money, and watched a firm do nothing. The anger is at the last firm, not you — but you inherit the burden of proof, and there’s something quieter underneath the anger: shame. They feel stupid for having been taken, and they’re braced for you to make them feel it again. So the first move is never a pitch. It’s “what happened?” — and then listening longer than feels efficient, because the retelling is what discharges the anger. The reframe that lands: their experience is data, not a verdict. It made them an educated buyer who now knows exactly which questions to ask — and a real firm survives every one of them. Then differentiate with process, not adjectives: “we’re different” is exactly what the last firm said. Verifiable actions with dates — POA filed, transcripts pulled, a compliance read delivered, all inside the first thirty days — are what a burned buyer can actually hold you to.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Take their side completely. Ask what happened, and let them tell all of it — the retelling discharges the anger, and interrupting it re-aims the anger at you.",
          "Feel-felt-found is built for this one: I get how you feel / half the people we help felt exactly that after their first firm / what they found was the difference is verifiable work in the first thirty days — see [[strat.feel-felt-found]].",
          "Differentiate with process transparency: name the first three concrete actions and their timing, in writing. Specifics are the anti-adjective.",
          "Ask what the last firm DIDN’T do — then address those exact gaps explicitly. Their bad experience becomes your checklist.",
          "Offer a smaller first commitment than usual. Earn the rest. A burned buyer shouldn’t have to bet everything twice.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "That’s infuriating, and it’s exactly why this industry has the reputation it does. What did they actually do before things stalled?",
          "Here’s how you protect yourself this time: everything we do in the first 30 days is specific and verifiable — transcripts, POA on file, compliance read. You’ll see each one happen.",
          "You know what that experience bought you? You now know exactly what questions to ask. Ask me all of them.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Don’t say “we’re different” with no substance — that’s the last firm’s script, and they’ve heard it.",
          "Don’t skip past the pain to pitch. The story has to come out first or nothing you say lands.",
          "Don’t add to the shame — no “you should have checked their reviews.” They’re braced for judgment; its absence is the trust-builder.",
        ],
      },
      {
        kind: "example",
        weak: "“I’m sorry that happened, but we’re totally different from those companies. We’re one of the most trusted names in tax resolution. So, about your balance—”",
        strong: "“That’s infuriating — you did the right thing and got robbed for it. What did they actually do before it stalled? … Okay. Here’s how you protect yourself this time: in the first thirty days you’ll see three specific things happen — POA filed, transcripts pulled, a written read of where you stand. Not promises. Things you can check.”",
        note: "The weak version rushes past the wound with adjectives. The strong one lets the story out, then replaces trust-me language with a verifiable checklist — the only currency a burned buyer accepts.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “The last company took four grand and I never heard from them again. Why would I ever do this twice?” What’s your move?",
        answer: "Take their side and get the story: what did they promise, what did they actually do? Listen fully. Then feel-felt-found, and differentiate with process — name the first three verifiable actions with timing, ask what the last firm never did, and address those gaps one by one. Offer a smaller first step than the full engagement. The play is earning, not asserting.",
      },
    ],
    links: [
      "strat.feel-felt-found",
      "strat.earn-trust-with-proof",
      "strat.shame-reduction",
      "obj.scam-distrust",
      "obj.hired-another-company",
      "script.expert",
    ],
  },
  {
    id: "obj.diy-self-rep",
    part: "objections",
    section: "capability",
    title: "“I’ll handle it myself / talk to the IRS directly”",
    aliases: [
      "handle it myself",
      "deal with them myself",
      "call the irs myself",
      "talk to the irs myself",
      "do it myself",
      "turbotax",
      "i can file myself",
      "do my own taxes",
      "figure it out myself",
      "i don't need a middleman",
    ],
    lead: "Pride, cost-saving, and a real fact: some simple cases ARE DIY-able — and you say so, out loud. Honor the right to self-represent, then show where the math changes: liens, levies, a revenue officer, payroll tax, audit. The angle is asymmetry of stakes, never their ability.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "Respect what’s underneath this: competence, self-reliance, and a fair suspicion of middlemen. And here’s the part weak agents can’t bring themselves to say — sometimes they’re right. One year, a small balance, no enforcement in motion? That person can call the IRS, set up a payment plan, and be fine. Telling them so is one of the strongest moves you have, because it proves you tell the truth even when it costs you. Then draw the honest line: the math changes with liens, levies, a revenue officer assignment, payroll tax, or an audit — see [[tax.levy-garnishment]] and [[tax.payroll-941-tfrp]]. The reframe isn’t “you can’t handle them” — that’s untrue and disrespectful. It’s asymmetry: the agent on that IRS line works for the IRS, everything said is recorded and usable, and they’ll be negotiating their first case against someone who has handled thousands. Representation flips who the system listens to. The takeaway close does the heavy lifting here: concede the simple case honestly and a defensive prospect will start arguing your side — “well, it’s actually four years…”",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Takeaway first (negative reverse): concede the simple case honestly — “if it’s one year and under ten grand, you might be right, you may not need anyone.” Watch them start arguing your side.",
          "Name the asymmetry, not their inability: they’ll be negotiating their first case against someone who’s done thousands — and disclosure rules bind THEM, not the IRS.",
          "Porcupine the confidence: “when you call them, what’s your plan when they ask for a full financial disclosure on a recorded line?” A better question keeps control — see [[strat.porcupine]].",
          "Draw the real line: self-rep is fine for a simple balance; liens, levies, an RO, payroll tax, or an audit is when the stakes outgrow the savings.",
          "Offer the diagnostic middle path: pull transcripts first — then they’ll KNOW if it’s a DIY case. Low commitment, real value, and it advances to sensitive info either way.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "If this were one year and a small balance, I’d tell you to handle it yourself — honestly. Multiple years with a levy notice? That’s when people calling the IRS alone say things that cost them.",
          "Here’s a middle path: we pull the transcripts and tell you exactly what you’re facing. If it’s simple, you’ll know. If it’s not, you’ll be glad you didn’t call them solo.",
          "One thing to keep in mind — the person who answers at the IRS works for the IRS, and that line is recorded. What’s your plan when they ask for a full financial disclosure?",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Never say “you can’t handle them yourself” — it’s untrue for simple cases and it insults their competence, which is the exact thing this objection runs on.",
          "Don’t pretend every case needs a firm. Overselling to a DIY-able case is how this industry earned its reputation — and they can smell it.",
          "Don’t out-argue their pride head-on. Concede ground first; the takeaway does what pushing can’t.",
        ],
      },
      {
        kind: "example",
        weak: "“Trust me, you don’t want to deal with the IRS yourself — they’ll eat you alive. People who go it alone always regret it.”",
        strong: "“Honestly? If this is one year and a small balance, handle it yourself — you’ll be fine and I’d tell you so. How many years are we talking, and has anything with a deadline shown up — lien notice, levy warning? … Four years and a levy notice is a different animal. That’s negotiating your first case ever against someone who’s done thousands, on a recorded line.”",
        note: "The weak version is fear plus a claim they know is false. The strong version concedes the simple case first — earning the credibility — then lets THEIR facts move the case across the line.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “I’m just going to call the IRS myself and set something up. I don’t need to pay somebody for that.” What’s your move?",
        answer: "Concede honestly: for a simple single-year balance, that’s exactly right and you’d tell them to do it. Then ask the scoping questions — how many years, any lien or levy notice, any revenue officer? If their answers cross the line, name the asymmetry (first case vs thousands, recorded line, one-way disclosure rules) and offer the transcript pull as the middle path that tells them which case they actually have.",
      },
    ],
    links: [
      "strat.takeaway",
      "strat.confident-value-frame",
      "psych.sandler.negative-reverse",
      "strat.porcupine",
      "tax.representation",
      "tax.levy-garnishment",
      "obj.oic-myself",
    ],
  },
  {
    id: "obj.oic-myself",
    part: "objections",
    section: "capability",
    title: "“I read I can do an Offer in Compromise myself for $205”",
    aliases: [
      "oic myself",
      "do the offer myself",
      "file my own offer in compromise",
      "205 dollar offer",
      "$205 application",
      "irs has a form for that",
      "fresh start program myself",
      "i saw it online",
    ],
    lead: "A sophisticated caller who did homework — and the homework is correct. The $205 application fee is real and anyone can file. Confirm it. The value-add isn’t the form; it’s the 433-A financial package, defensible offer math, the negotiation, and the appeal if it’s rejected.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "Treat this prospect as what they usually are: a researcher testing whether you’ll lie to them. They found the real IRS fee, and if your first move is “that won’t work,” you fail the test — because sometimes it does work, and they may know that too. So confirm their facts first: yes, the application fee is real; yes, anyone can file one. That honesty is the whole opening. Then teach where the work actually lives. An OIC isn’t a form — it’s a financial case. The Form 433-A OIC package is a full disclosure of income, assets, and allowable expenses; the offer amount has to be computed from that math in a way the IRS unit will find defensible; then there’s the back-and-forth when they push back, and the appeal when a defensible offer still gets rejected. Most DIY offers die not because the taxpayer wasn’t allowed to file, but because the number wasn’t built to survive review. That framing respects their research and reframes the fee as buying the case, not the paperwork — see [[tax.resolution-options]].",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Confirm their research immediately and specifically — “you’re right, the fee is real, anyone can file.” Passing the honesty test is the door into everything else.",
          "Relocate the value: the application is the cheapest part. The case is the 433-A financial package, the offer math, the negotiation, and the appeal if rejected.",
          "Explain why DIY offers fail: not eligibility — construction. An offer number the IRS math doesn’t support gets rejected after months of waiting, and a rejected offer means months of accrued penalties and a file that’s now been fully disclosed.",
          "Porcupine their plan: “when you compute your offer amount, how are you going to calculate your reasonable collection potential?” If the term is new to them, the gap just introduced itself.",
          "Offer the qualification check as the advance: transcripts and a financial review say whether an OIC is even their best door — sometimes another program beats it, and only the math knows.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "You did real homework — that fee is exactly right, and anyone can file one. The $205 is the cheapest part of the whole thing, though. The offer lives or dies on the financial package behind it.",
          "Here’s what actually decides it: the IRS computes what they think they can collect from you, and your offer has to beat that math in a way they’ll accept. Get that number wrong and you wait months for a rejection — with penalties running the whole time.",
          "Before you spend the $205, it’s worth knowing whether an offer is even your best door. Your transcripts and a financial review answer that. If DIY makes sense after that, you’ll know it does.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Never say “it won’t work” — sometimes it will, they may know it, and the lie costs you the sophisticated buyer forever.",
          "Don’t belittle the research. This caller is engaged and informed — that’s a buying signal, not a threat.",
          "Never promise their offer will be accepted with us either — acceptance is the IRS’s call, always.",
        ],
      },
      {
        kind: "example",
        weak: "“Yeah, people try that. It never works — the IRS rejects almost all of those. You need professionals for an OIC.”",
        strong: "“You’re right — $205, and anyone can file. Here’s the part the article skips: the offer is really a financial case. The 433-A package, the offer math the IRS unit has to accept, the pushback, the appeal if they reject a good offer anyway. Question worth answering before you spend anything: is an OIC even your best program? Your transcripts settle that in a week.”",
        note: "The weak version leads with a half-truth the researcher can catch. The strong version confirms their facts, relocates the value from form to case, and converts the objection into a qualification step.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “The IRS website says I can file an offer myself. Why would I pay you thousands for a $205 form?” What’s your move?",
        answer: "Confirm it — the fee’s real, filing is open to anyone, and say so first. Then reframe: they’re not paying for the form, they’re paying for the case behind it — the 433-A package, a defensible offer number, negotiation, and appeal. Ask how they plan to compute their reasonable collection potential; then offer the transcript-and-financials review that says whether an OIC is even their best door.",
      },
      {
        kind: "compliance",
        text: "Never promise an offer will be accepted, never quote a settlement percentage, and never frame the OIC as “pennies on the dollar.” Acceptance is the IRS’s decision based on the taxpayer’s actual financials. What we commit to is the work: the package, the math, the negotiation, the appeal.",
      },
    ],
    links: [
      "tax.resolution-options",
      "strat.expert-specificity",
      "strat.confident-value-frame",
      "obj.diy-self-rep",
      "obj.guarantee-seeking",
    ],
  },
  {
    id: "obj.licensed-question",
    part: "objections",
    section: "capability",
    title: "“Are you licensed to represent me before the IRS?”",
    aliases: [
      "are you licensed",
      "are you an enrolled agent",
      "is there a cpa on staff",
      "do you have attorneys",
      "who actually represents me",
      "what are your credentials",
      "can you legally represent me",
    ],
    lead: "A sophisticated caller — they know only an EA, CPA, or attorney can represent a taxpayer before the IRS, and they’re checking whether you know it too. Vagueness kills this call. Name the licensed professionals specifically and offer the introduction.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "This question is a credential check from someone who did their reading — they know representation before the IRS is limited to enrolled agents, CPAs, and attorneys, and they know a boiler room when a rep gets fuzzy about it. So understand your own role cleanly: you, the person on this call, are not their representative — the licensed professionals on staff are, operating under the power of attorney in [[tax.representation]]. Saying that plainly is not a weakness; it’s the correct answer, and the sophisticated caller knows it. A vague “oh yeah, we’re fully licensed” is exactly the hedge they’re listening for. The strong play is specificity plus access: name the credential types on staff — enrolled agents, tax preparers, and other tax specialists, with enrolled agents handling IRS representation — explain who signs the POA and does the negotiating, and offer to introduce them, on this call or right after engagement. An agent who offers the introduction unprompted has nothing to hide, and this prospect closes on exactly that.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Answer directly and specifically — name the licensed roles on staff (enrolled agents, tax preparers, and other tax specialists). No hedging, no “basically.”",
          "Clarify the structure honestly: your job is the intake and the fit; the licensed professional signs the power of attorney and stands before the IRS. Precision here reads as competence, not smallness.",
          "Offer the introduction: “I can get one of our enrolled agents on the line, or you’ll be introduced the day your case opens.” Access is the proof.",
          "Invite verification — EA enrollment and CPA/bar licenses are checkable, and telling them how to check is a trust move only a legitimate firm can make.",
          "Then advance: the credential question answered, bridge back to their case — the license matters because of what it lets us do on their file.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "Good question, and I’ll answer it straight: I’m your point of contact, and the people who represent you before the IRS are our licensed staff — enrolled agents, supported by tax preparers and other tax specialists. An enrolled agent signs your power of attorney, not me.",
          "Want to talk to one? I can set that up. And their credentials are verifiable — EA enrollment and CPA licenses are public. Check before you send a dollar.",
          "You clearly know how representation works, so you know why it matters: the POA is what makes the IRS deal with our licensed rep instead of with you.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "No vague answers — “we’re totally licensed” without naming credentials is the hedge this caller is testing for.",
          "Don’t imply that you personally are the representative if you’re not. This prospect may know the rules better than a new agent does.",
          "Don’t get defensive about the question. It’s a buying signal from a careful buyer — welcome it.",
        ],
      },
      {
        kind: "example",
        weak: "“Oh yeah, we’re fully licensed, we handle IRS stuff all day. Don’t worry about that part.”",
        strong: "“Straight answer: I’m your intake contact — the representation itself is done by our licensed staff — enrolled agents, with tax preparers and other tax specialists behind them. An enrolled agent signs your power of attorney. If you want, I’ll get an EA on the line before you commit to anything, and every credential I just named is publicly verifiable.”",
        note: "The weak version hedges on the exact point being tested. The strong version names credentials, draws the honest line between intake and representation, and offers access plus verification — the three things a sophisticated caller is actually shopping for.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “Are YOU an enrolled agent? Because only an EA, CPA, or attorney can actually represent me.” What’s your move?",
        answer: "Tell the truth cleanly: no — you’re their point of contact, and the representation is done by the licensed staff, whom you name by credential type. Offer to put an enrolled agent on the line and point them to where the credentials can be verified. Then bridge: the reason the license matters is the POA it powers, which is the first thing that goes on file for their case.",
      },
    ],
    links: [
      "tax.representation",
      "psych.cialdini.authority",
      "strat.expert-specificity",
      "strat.earn-trust-with-proof",
      "obj.how-can-i-trust",
    ],
  },
  {
    id: "obj.success-rate",
    part: "objections",
    section: "capability",
    title: "“What’s your success rate?”",
    aliases: [
      "success rate",
      "how often do you win",
      "what percentage",
      "how many cases do you settle",
      "do you usually get results",
      "what are the odds",
      "track record",
    ],
    lead: "They want a number to anchor on — and any number you invent is a lie that will eventually surface. Define “success” first, give honest ranges with case-by-case caveats, and let the refusal to fabricate be the credibility move it is.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "The prospect is trying to reduce an unfamiliar decision to one familiar number. Reasonable instinct — but the question is broken as asked, and the strong play is to say so before answering. Success at WHAT? A levy released, an installment agreement that actually fits, penalties abated, an offer accepted, hardship status granted? Those are different outcomes with different odds that depend almost entirely on the individual case’s facts — income, assets, years, compliance status. A firm that answers “92%” without asking “92% of what, for whom?” is telling the caller what they want to hear, and this is exactly where the industry’s liars live: made-up rates and “pennies on the dollar” averages. So define success first, then give honest, hedged reality: outcomes vary by case, some programs are common and some are rare, and what determines THEIR odds is THEIR transcript and THEIR financials — which is a thing we can actually find out, unlike a marketing statistic. The refusal to invent a number is not a dodge. Said with confidence, it is the answer.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Define success before quoting anything: “success at what — a levy release, a payment plan that fits, an offer accepted? Those are different questions.” Precision immediately outclasses every competitor’s fake stat.",
          "Give honest shape, not fiction: some outcomes are routine when the case supports them, others (like accepted OICs) are genuinely case-dependent — see [[tax.resolution-options]] for the honest framing of each program.",
          "Name the manipulation they’ve been marketed: firms quoting high settlement percentages are averaging cherry-picked cases or making it up. Saying this out loud puts you on the caller’s side of the table.",
          "Pivot from population odds to THEIR odds: the statistic that matters is what their transcript and financials qualify them for — and that’s discoverable, this week, not a brochure claim.",
          "Offer the accountability substitute: we can’t promise a rate, but we can commit to verifiable actions and honest reporting of what the file shows at every step.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "Success at what? Getting a levy released is a different question from getting an offer accepted. Tell me which one you’re asking about and I’ll give you a straight answer for it.",
          "Anyone who gives you one clean percentage for the whole business is selling you. The honest answer is that it depends on the case — and the good news is your case is checkable. Your transcripts tell us what you actually qualify for.",
          "Here’s the number I can stand behind: once your transcripts come back — that part runs on the IRS’s clock — you’ll know exactly which programs your file supports. That’s not a rate — it’s a commitment.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Never invent a number. Never. A fabricated rate is a compliance problem and a time bomb in the client relationship.",
          "Never say “100%” or anything near it — instant credibility death with any caller worth having.",
          "Don’t dodge the question either — “we don’t discuss that” reads as hiding. Reframe it and answer the better version.",
        ],
      },
      {
        kind: "example",
        weak: "“We have about a 95% success rate — our clients almost always save money. You’re in good hands.”",
        strong: "“Depends what you mean by success — and that’s not a dodge, it’s the real answer. Levy releases and workable payment plans are routine when the case supports them. Accepted offers are rarer and depend entirely on your financials. Anyone who quotes you one big percentage for everything is marketing at you. What I can do is find out YOUR odds — that’s what the transcripts are for.”",
        note: "The weak version fabricates — a lie the client eventually catches and a compliance breach today. The strong version redefines the question, gives honest ranges per outcome, calls out the industry’s fake-stat habit, and converts the question into the transcript advance.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “The other company I called said they settle 90% of cases for less than half. What’s YOUR rate?” What’s your move?",
        answer: "Name what just happened: a blanket settlement percentage across all cases is a marketing number, not a case number — and that framing gently warns them about the other firm without trash-talk. Then define success by outcome, give the honest case-by-case shape, and pivot: the only rate that matters is what their file qualifies for, which the transcript pull answers as fact.",
      },
      {
        kind: "compliance",
        text: "Never state, imply, or improvise a success rate, savings percentage, or average settlement figure. No number of this kind exists in approved materials because no honest single number exists. What we commit to is process — representation filed, transcripts reviewed, qualification assessed on the actual financials — never a statistical promise of outcome.",
      },
    ],
    links: [
      "obj.guarantee-seeking",
      "tax.resolution-options",
      "strat.earn-trust-with-proof",
      "strat.expert-specificity",
      "obj.how-can-i-trust",
    ],
  },
  {
    id: "obj.will-it-make-worse",
    part: "objections",
    section: "capability",
    title: "“Will hiring you make the IRS come after me harder?”",
    aliases: [
      "will it make things worse",
      "will they retaliate",
      "will the irs know you're calling",
      "red flag with the irs",
      "don't want to poke the bear",
      "wake the sleeping giant",
      "put me on their radar",
      "draw attention to myself",
    ],
    lead: "Fear of retaliation — they think hiring help “pokes the bear.” The honest reassurance is the opposite: the IRS treats represented taxpayers professionally, and a POA on file often slows aggressive collection. Never dismiss the fear; answer it with how the system actually works.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "This prospect has been surviving on invisibility. Their working theory is that the IRS hasn’t crushed them yet because the IRS hasn’t noticed them yet — so anything that announces “I’m here and I lawyered up” feels like painting a target on their own back. The fear is sincere and it deserves a real answer, not a brush-off, because dismissing it (“oh no, that never happens”) leaves the fear intact and just adds distrust of you. The truth is better than reassurance anyway: the IRS is not an insulted person, it’s a system, and the system already knows about them — the balance is assessed and the collections track runs on its own clock whether they hide or not (see [[tax.collections-ladder]]). What a power of attorney changes is the channel: notices and contact route through the representative, represented taxpayers are handled professionally as a matter of standard procedure, and in many cases active representation slows aggressive collection because there is now someone requesting holds, filing appeals, and getting deadlines honored. Hiding is not protection. Hiding is just facing the same machine with no one at the controls on your side.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Validate the fear first — “a lot of people worry exactly that” — before correcting it. A dismissed fear digs in; an acknowledged one can be taught.",
          "Correct the premise: the IRS already knows. The balance is assessed and the collection clock runs regardless — silence isn’t stealth, it’s just undefended.",
          "Explain what the POA actually does: contact routes through the representative, and represented taxpayers are handled professionally as standard procedure — not as a grudge match.",
          "Give the counterintuitive truth: representation often SLOWS aggressive collection — holds get requested, appeal rights get exercised, deadlines get met — where an unrepresented file just rolls down the enforcement track.",
          "Advance on the relief: the first thing representation buys is that they stop facing the IRS alone — the transcript pull and POA are the first concrete steps of that.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "I get the instinct — don’t poke the bear. Here’s the thing though: the bear already has your file. The balance is assessed and their clock is running whether you’re quiet or not.",
          "Hiring representation doesn’t read as defiance to the IRS — it reads as normal. They deal with representatives all day, and honestly, files with a POA tend to get handled MORE professionally, not less.",
          "Think about what changes the day the POA goes on file: their calls and letters route through us, and there’s finally someone whose whole job is pumping the brakes on your case. That’s the opposite of making it worse.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Don’t dismiss the concern with a wave — “that’s silly, they don’t do that” invalidates them and answers nothing.",
          "Don’t overcorrect into a promise — never guarantee that collection will stop or that a hold will be granted. Say what representation does, not what the IRS will decide.",
          "Don’t feed the fear to force urgency — “they’re about to come for you” is the fear-monger move and it poisons the trust you just built.",
        ],
      },
      {
        kind: "example",
        weak: "“No, no, that’s not a thing, don’t worry about it. The IRS doesn’t care. So anyway, about getting you signed up—”",
        strong: "“That’s a really common worry, and I get why — you’ve stayed off the radar this long. But here’s the honest picture: you’re already ON the radar. The balance is assessed and their process runs on its own clock. What the power of attorney changes is who they have to deal with — and represented files get handled professionally, often more slowly on the enforcement side, because now someone’s filing the holds and working the deadlines.”",
        note: "The weak version dismisses the fear and lunges for the close. The strong version validates it, corrects the invisible-so-safe premise, and explains the mechanism — which turns the fear itself into the reason to get represented.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “If your firm contacts the IRS about me, won’t that just flag my file and speed everything up?” What’s your move?",
        answer: "Validate the worry, then correct the premise: the file is already flagged — assessment happened, the collections ladder runs on its own schedule. Explain the POA mechanism: contact routes through the representative, represented taxpayers get standard professional handling, and representation is often what slows aggressive collection because someone is finally requesting holds and exercising appeal rights. No promises about what the IRS will grant — just what we do.",
      },
      {
        kind: "compliance",
        text: "Reassure with mechanism, never with promises: say what representation does (POA on file, contact routed through us, holds requested, appeals filed) — never that the IRS will pause collection, release a levy, or go easier. Those are the IRS’s decisions, and promising them is the line we do not cross.",
      },
    ],
    links: [
      "tax.representation",
      "tax.collections-ladder",
      "strat.human-reassurance",
      "strat.calm-urgency",
      "obj.no-urgency",
    ],
  },
  {
    id: "obj.how-long",
    part: "objections",
    section: "capability",
    title: "“How long will this take?”",
    aliases: [
      "how long does it take",
      "how long will this take",
      "how fast can you fix this",
      "when will it be resolved",
      "is this going to drag on",
      "how quickly can you stop the levy",
      "timeline",
    ],
    lead: "Pain-timeline anxiety — and often a buying signal in disguise. Answer with honest ranges: protection actions happen in days, full resolution takes months. Say what happens FIRST. A false speed claim closes today and detonates in week five.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "Someone asking “how long” is often already picturing the other side of this — which makes it, more often than not, a buying signal wearing a question’s clothes. But it’s powered by anxiety: they’ve been carrying this weight and they want to know when it comes off. The temptation is to say what they want to hear — “thirty days, easy” — and that lie has a fuse on it: the client who was promised thirty days becomes the furious review-writer in week five, and worse, they may make real decisions (ignoring a notice, skipping a payment) based on your fake timeline. The honest answer is genuinely satisfying if you structure it right, because the truth has a fast part: protection moves quickly — power of attorney on file within days, transcripts requested, contact rerouted through the firm, holds requested where enforcement is active. That’s when the phone stops being scary. Resolution — the installment agreement, the offer, hardship status — is a months-scale process because it runs on IRS review timelines nobody controls. Lead with what happens FIRST and in what order, and the months stop feeling like fog and start feeling like a plan. See [[tax.resolution-options]] for what each track involves.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Treat it as the buying signal it is — answer the momentum, warmly and directly. Never dodge a timeline question; evasion reads as “forever.”",
          "Split the answer in two: protection in days, resolution in months. Two honest clocks beat one fake one.",
          "Say what happens FIRST, concretely: POA filed, transcripts pulled, compliance read delivered, holds requested where something’s actively in motion. Sequence kills anxiety better than speed claims do.",
          "Anchor the long clock honestly: the resolution phase runs on IRS review timelines — which is exactly why starting the fast part now matters. The cost of waiting compounds; see [[strat.cost-of-waiting]].",
          "Close the loop with the next step: “the days-clock starts when the POA goes on file — let’s start it.” The timeline question becomes the close.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "Two honest clocks. The protection part starts today — filing the power of attorney is what gets you protected, and from there their letters and calls come to us, not you. The resolution part — the actual deal with the IRS — is months, because it runs on their review timelines, not ours.",
          "Here’s what happens first, in order: POA filed, transcripts pulled, and a straight read of where you stand — usually inside the first couple of weeks. You’ll know your whole picture before the first month is out.",
          "Anyone who tells you thirty days for the whole thing is telling you what you want to hear. What I’ll tell you instead is what happens in the first two weeks — and every bit of it is checkable.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "No false speed claims — never “it’ll be done in 30 days.” That promise closes one deal and manufactures one enraged client.",
          "Don’t give one vague blob — “it varies, could be a while” answers nothing and reads as evasive. Split the clocks and be specific about the fast one.",
          "Don’t promise a specific date for anything the IRS controls — holds, agreements, offer decisions. Our actions get dates; their decisions get ranges.",
        ],
      },
      {
        kind: "example",
        weak: "“Oh, we move fast — most cases wrap up in about a month. You’ll be done with this before you know it.”",
        strong: "“Straight answer, two parts. The protection is fast: POA on file within days, and from then on the IRS deals with us — that’s when your mailbox stops being a threat. The full resolution is a months-scale process, because the IRS reviews on their clock, not ours. But you’ll know exactly where you stand within the first few weeks, and every step before that is on a schedule I can name.”",
        note: "The weak version buys today’s yes with week-five’s explosion. The strong version gives the anxious buyer the thing they actually need — a fast first clock, a truthful long one, and a named sequence — without promising anything the IRS controls.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “My paycheck is being garnished RIGHT NOW. How fast can you stop it?” What’s your move?",
        answer: "Honor the urgency and split the clocks honestly: what WE do moves in days — POA filed immediately, garnishment addressed as the first order of business, release requested with the levy unit. What you never do is promise the release or a date for it, because that’s the IRS’s decision. Give the sequence, start the fast clock today, and let the concrete first steps carry the reassurance a fake promise would have faked.",
      },
      {
        kind: "compliance",
        text: "Dates for our actions, ranges for theirs. We can commit to when the POA gets filed and when transcripts get requested; we never commit to when the IRS will grant a hold, release a levy, or approve anything. A promised date on an IRS decision is a promised result — and we don’t promise results.",
      },
    ],
    links: [
      "strat.answer-the-momentum",
      "strat.cost-of-waiting",
      "strat.calm-urgency",
      "tax.resolution-options",
      "tax.levy-garnishment",
      "script.pitch",
    ],
  },

  // ── debt ──────────────────────────────────────────────────────────────────
  {
    id: "obj.dont-owe",
    part: "objections",
    section: "debt",
    title: "“I’m not sure I even owe this / I don’t think I have a tax problem”",
    aliases: [
      "i don't owe that",
      "i'm not sure i owe",
      "i don't think i owe anything",
      "i don't have a tax problem",
      "that number can't be right",
      "the irs made a mistake",
      "i never got a bill",
    ],
    lead: "Confusion, denial, or a legitimate concern — SFR-based assessments and identity issues are real. Don’t argue that they owe. The play is “let’s find out together”: pull the transcripts and see exactly what the IRS shows. If there’s no debt, they don’t need us — and saying so is the close.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "Never treat this as a dodge, because a meaningful slice of the time it’s a fair point. Assessments really are wrong sometimes: the IRS files substitute returns for non-filers — single, zero deductions, worst possible math (see [[tax.unfiled-sfr]]) — identity theft creates phantom balances, and old liens can trail a resolved debt. The rest of the time it’s denial or genuine confusion, and here’s the beautiful part: the play is identical in every case. You don’t need to know which one you’re holding, and you should never argue “yes you do, the IRS doesn’t make mistakes” — it does, and saying otherwise costs you both truth and trust. Instead: “let’s find out together.” The transcript pull shows exactly what the IRS has on file — every assessment, every year, every source. If the debt is real, they just learned it from evidence instead of from your insistence, and you’re already the person who helped them face it. If there’s no debt, you say the magic words: “then you don’t need us” — and that honesty is what they’ll remember, repeat, and refer.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Agree that it’s worth verifying — never argue the debt into existence. “You might be right” is the disarm that makes everything after it possible.",
          "Name the legitimate ways an assessment goes wrong: substitute-for-return filings, identity theft, misapplied payments, a lien that outlived its debt. Knowing the failure modes proves you’re a diagnostician, not a script.",
          "Propose the joint investigation: “let’s find out together — we pull your transcripts and see exactly what the IRS shows.” It’s the same advance as every other path, reached through their own doubt.",
          "Deliver the no-debt guarantee of honesty out loud: “and if there’s no debt on file, you don’t need us — I’ll tell you that in plain English.” That sentence closes more of these than any pressure could.",
          "Anchor to the paper if it exists: if they got a notice or a lien filing, something generated it — the transcript says what, and ignoring it doesn’t make it wrong OR right.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "You might be right — assessments get botched more than people think. Let’s find out together: we pull your transcripts and see exactly what the IRS has on file. If there’s no debt there, you don’t need us, and I’ll say so.",
          "Here’s one way that number shows up wrong: you skip a filing year, and the IRS files FOR you — single, zero deductions, worst math possible. If that’s what happened, the fix is a real return, not a payment plan.",
          "Something generated that letter. Could be a real balance, could be a mistake, could be someone using your Social. The transcript doesn’t guess — it just says.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Never say “yes you do — the IRS doesn’t make mistakes.” It does, they may know a story where it did, and you just picked a fight you can’t win.",
          "Don’t push past the doubt to pitch resolution services for a debt they don’t accept exists. Verify first; the pitch order matters.",
          "Don’t dismiss it as denial — even when it is, the transcript play works, and the accusation never does.",
        ],
      },
      {
        kind: "example",
        weak: "“Sir, if the IRS says you owe it, you owe it. They don’t send letters for fun. Now, about resolving this balance—”",
        strong: "“Honestly, you might be right — wrong assessments happen. Substitute returns, identity theft, misapplied payments — we see all of them. So let’s not guess: we pull your transcripts and read exactly what the IRS has. If there’s a real balance, you’ll see it in black and white. If there isn’t — then you don’t need us, and I’ll be the one to tell you.”",
        note: "The weak version argues for the debt, which makes the agent the adversary. The strong version joins the prospect’s skepticism, names real failure modes, and makes honesty the offer — with the transcript pull as the advance either way.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “I got a letter saying I owe $28,000 but that’s impossible — I always got refunds. This has to be a mistake.” What’s your move?",
        answer: "Don’t defend the number — join the doubt: “could be, and there’s a specific way that happens.” Ask if there are any unfiled years — a substitute return with zero deductions inflates a balance exactly like this. Then the joint investigation: pull the transcripts and see what generated the $28,000. Real balance, SFR to correct, or an error to dispute — the paper decides, and if there’s truly no debt, they don’t need us and you say so.",
      },
    ],
    links: [
      "tax.unfiled-sfr",
      "strat.earn-trust-with-proof",
      "strat.agree-first",
      "script.discovery",
      "obj.not-my-debt",
      "obj.debt-expired-csed",
    ],
  },
  {
    id: "obj.not-my-debt",
    part: "objections",
    section: "debt",
    title: "“This isn’t my debt — it’s my ex’s / my late spouse’s”",
    aliases: [
      "that's my ex's debt",
      "my ex husband owes that",
      "my ex wife did that",
      "my late husband's taxes",
      "my deceased spouse",
      "that was before we married",
      "i didn't file that return",
      "someone used my social",
      "identity theft",
    ],
    lead: "Could be innocent-spouse relief, identity theft, or denial — and the difference is diagnostic, not rhetorical. Ask the right questions: joint return? Which year? Are they on the assessment? Name the real remedies (Form 8857, identity-theft procedures) without promising they’ll qualify.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "This objection carries a genuine legal question inside it, and treating it as a routine brush-off is malpractice-grade sloppiness. When spouses file jointly, both are on the hook for the whole balance — which means an ex’s underreporting or a late spouse’s debt can legitimately land on this caller, AND there are real remedies built for exactly that: innocent spouse relief (Form 8857) when one spouse didn’t know about the other’s errors, injured spouse claims when a refund got taken for a partner’s separate debt, identity-theft procedures when someone filed using their Social. Which door applies is a facts question, so the play is diagnostic: was it a joint return? What year is the debt from — during the marriage or before it? Is the caller actually named on the assessment? The trap on the other side is overpromising — “oh, innocent spouse, easy, we’ll get you off that” is a result-promise about a determination the IRS makes on evidence. Name the remedy as a path that exists, make qualifying a question the transcripts and facts will answer, and the emotional payload — being chased for someone else’s mess — becomes the motive power for the advance.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Take the claim seriously first — “if that’s someone else’s debt, that matters legally, so let’s get the facts right.” Respect for the claim earns the right to test it.",
          "Run the diagnostics in order: joint return or separate? What tax year — during the marriage, before, after? Are they actually named on the assessment, or just receiving mail for someone who is?",
          "Name the doors that exist without promising any of them opens: innocent spouse relief (Form 8857), injured spouse claims, identity-theft procedures. The remedy names prove this is a known, solvable category.",
          "Distinguish the deceased-spouse case: estate and joint-liability rules differ — the answer lives in how the returns were filed, which the transcripts show.",
          "Advance on the verification: the transcript shows whose assessment it is, from what filing, for what year — the one document that turns “not mine” from a plea into a case.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "If that’s really your ex’s debt, that matters — there’s actual relief built for that situation. First question: were those joint returns, or did you file separately?",
          "There’s a thing called innocent spouse relief — Form 8857 — for exactly this: one spouse gets stuck with the other’s tax mess. Whether you qualify depends on the facts, and the facts start with your transcript.",
          "Being billed for it and legally owing it are not the same thing. The transcript shows whose assessment it actually is. Let’s pull it and see which fight you’re actually in.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Don’t skip the substantive issue and treat this as a routine stall — there may be a real legal remedy sitting in this call.",
          "Don’t overpromise the remedy — “we’ll get you innocent-spouse relief” is a result-promise about an IRS determination. Name the path, not the outcome.",
          "Don’t adjudicate the marriage. Whose fault the debt is emotionally is not the question; whose name is on the assessment is.",
        ],
      },
      {
        kind: "example",
        weak: "“Unfortunately if it’s got your name on it, it’s your problem now. The IRS doesn’t care whose fault it was. So let’s talk about resolving it—”",
        strong: "“Hold on — if that’s genuinely your ex’s debt, there’s relief built for exactly this, so let’s get the facts straight. Were those joint returns? And what year is the balance from? … Okay: joint return during the marriage means you’re on the assessment, but it also means innocent spouse relief is potentially on the table — Form 8857, for spouses who didn’t know what the other was doing. Whether you qualify is a facts question, and the transcript is where the facts live.”",
        note: "The weak version concedes their worst fear and pivots to a pitch — brutal and wrong on the law. The strong version diagnoses, names the actual remedy without promising it, and makes the transcript the natural next step.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “This $40,000 is from my ex-husband’s business. We divorced three years ago — the judge even said the taxes were his. Why is the IRS coming after ME?” What’s your move?",
        answer: "Explain the painful truth gently: a divorce decree binds the exes, not the IRS — on a joint return, both spouses owe the whole balance regardless of what the judge assigned. Then the door: that exact situation is what innocent spouse relief exists for, and equitable-relief factors even consider the divorce decree. Diagnose — joint returns? Which years? Did she know about the business income? — and advance to the transcript pull that starts the actual case. Never promise the relief will be granted.",
      },
      {
        kind: "compliance",
        text: "Name remedies as paths, never as outcomes: innocent spouse relief, injured spouse claims, and identity-theft procedures exist — whether this caller qualifies is the IRS’s determination on the facts. “There’s relief built for this and we’ll find out if you qualify” is the line; “we’ll get you off this debt” is the violation.",
      },
    ],
    links: [
      "tax.representation",
      "strat.clarify-without-overfitting",
      "strat.human-reassurance",
      "script.discovery",
      "obj.dont-owe",
    ],
  },
  {
    id: "obj.debt-expired-csed",
    part: "objections",
    section: "debt",
    title: "“This debt is from years ago — isn’t it expired by now?”",
    aliases: [
      "isn't it expired",
      "statute of limitations",
      "ten year rule",
      "10 year rule",
      "too old to collect",
      "csed",
      "that debt is ancient",
      "they can't still collect that",
      "doesn't tax debt expire",
    ],
    lead: "They’ve heard about the CSED — and it’s real: the IRS generally has 10 years from assessment to collect. But tolling events stretch it, and nobody knows THEIR date without the transcript. Never answer yes or no from the hip; the verified date is the product.",
    blocks: [
      {
        kind: "prose",
        heading: "What it really means",
        text: "This caller did some reading, and the reading is right as far as it goes: the Collection Statute Expiration Date is real — the IRS generally gets ten years from the date of assessment to collect, and balances genuinely do die (see [[tax.csed]]). Confirming that immediately is the credibility move; a rep who denies the CSED exists just failed a test the prospect knew the answer to. But two details turn this from trivia into a case. First, the clock runs from ASSESSMENT, not from the tax year — a 2014 debt assessed in 2017 runs to 2027. Second, the clock PAUSES: a pending offer in compromise, a Collection Due Process hearing, bankruptcy, time outside the country — each tolling event freezes the countdown and tacks the frozen time onto the end. The people most likely to think they’re past the line are exactly the people who filed an OIC once or sat in bankruptcy — the moves that stretched their own clock. So the answer is never a yes or a no from the hip; either guess can be catastrophically wrong in a different direction. The answer is a date, the date is computed from the transcript, and — honesty being the play — if the transcript says the debt IS expired or nearly so, you tell them, because sometimes running out the clock really is the strategy, and only the transcript knows whose strategy it is.",
      },
      {
        kind: "moves",
        heading: "The plays, in order",
        items: [
          "Confirm the rule immediately: yes, the CSED is real — ten years from assessment, and debts genuinely do expire. Passing their knowledge test is what earns the “but.”",
          "Correct the clock’s start: it runs from the assessment date, not the tax year — a debt “from 2014” can have a much younger clock than they think.",
          "Name the tolling events plainly: a pending OIC, a CDP hearing, bankruptcy, time out of the country — each one paused their clock and extended the deadline, and the prospect rarely knows which ones hit their file.",
          "Refuse the hip-shot: never a bare yes or no. Guessing “expired” invites them to ignore a live, collectible debt; guessing “not expired” might sell them services against a corpse. Both are malpractice.",
          "Advance to the verification: the exact CSED per assessment is computable from the transcript. If it’s expired or nearly so, you say so — sometimes waiting IS the strategy, and telling them that is what makes everything else you say true.",
        ],
      },
      {
        kind: "lines",
        heading: "Lines in the floor’s voice",
        items: [
          "You’re right that it’s real — the IRS gets ten years from assessment, and debts do die. The catch is the clock: it starts at assessment, not the tax year, and it PAUSES — an offer in compromise, a hearing, a bankruptcy all freeze it and add time on the back.",
          "I’m not going to guess yes or no on your expiration date — either guess can hurt you. The actual date, per assessment, is sitting on your transcript. Let’s pull it and read the real number.",
          "Honestly, for some people waiting is the right move — the clock runs out and that’s that. Want to know if that’s you? The dates are on the transcript. If you’re one of the lucky ones, I’ll tell you so.",
        ],
      },
      {
        kind: "avoid",
        heading: "What not to do",
        items: [
          "Never answer “no, it’s not expired” or “yes, it’s expired” without checking — either hip-shot can be badly wrong, in opposite and equally damaging ways.",
          "Don’t deny the CSED exists or wave it off — the caller may know the rule, and denying it torches your expertise on the spot.",
          "Don’t pitch resolution services against a balance that might be months from expiring without verifying first — selling against a dying debt is the kind of thing burned-buyer stories are made of.",
        ],
      },
      {
        kind: "example",
        weak: "“No, tax debt doesn’t really expire — the IRS always finds a way to collect. That’s a myth. Now, about this balance—”",
        strong: "“Good instinct — that rule is real. Ten years from assessment and the debt dies. Two catches, though: the clock starts when they assessed it, not the tax year — and it pauses. Ever file an offer in compromise, have a hearing, go through bankruptcy? Each of those froze your clock and added time. Your actual expiration dates are on your transcript, per assessment. Let’s pull them — and if you’re close to the line, I’ll tell you, because for some people waiting IS the play.”",
        note: "The weak version denies a real rule the caller may know — instant credibility death. The strong version confirms the rule, teaches the two catches, refuses to guess, and offers the honest promise that makes the transcript pull irresistible: whatever the dates say, they get the truth.",
      },
      {
        kind: "drill",
        prompt: "Prospect says: “That debt’s from 2015 — it’s been ten years, so they can’t collect it anymore, right?” What’s your move?",
        answer: "Confirm the rule, then teach the two catches: the ten years run from assessment (which may be well after 2015, especially if the return was filed late or the IRS filed for them), and tolling events — an OIC, a CDP hearing, bankruptcy — pause the clock and extend it. Ask whether any of those happened. Then refuse to guess and advance: the exact CSED per assessment is on the transcript, and if the debt really is expired or nearly so, you’ll tell them straight — including if the right move is to wait.",
      },
      {
        kind: "compliance",
        text: "Never declare a debt expired or collectible without the transcript — a wrong answer in either direction causes real financial harm. The CSED explanation stays general (ten years from assessment, tolling events exist); the caller’s specific dates come only from their verified transcript, and if the file says the debt is dead or dying, they get told.",
      },
    ],
    links: [
      "tax.csed",
      "tax.unfiled-sfr",
      "obj.no-urgency",
      "obj.dont-owe",
      "strat.expert-specificity",
      "strat.takeaway",
    ],
  },
];
