import type { ManualEntry } from "./types";

export const TAX_ENTRIES: ManualEntry[] = [
  {
    id: "tax.collections-ladder",
    part: "script",
    section: "tax",
    title: "The collections ladder: CP14 → CP504 → LT11 / Letter 1058",
    aliases: [
      "IRS notice",
      "CP14",
      "CP504",
      "LT11",
      "Letter 1058",
      "final notice",
      "intent to levy",
      "certified letter",
      "collection notice",
    ],
    lead: "IRS collections is a ladder, not a lightning bolt. Each letter is a rung — and knowing which rung the prospect is standing on tells you exactly how much real, honest urgency the call carries.",
    blocks: [
      {
        kind: "prose",
        heading: "How the ladder works",
        text: "The IRS does not go from “you owe money” to “we took your paycheck” in one step. It escalates through notices, and each one has a specific legal meaning. CP14 is the first bill — a balance-due notice, the opening move. If it goes unanswered, reminder notices follow (CP501, CP503), and then CP504: the Notice of Intent to Levy. That word “intent” matters — the IRS is formally telling the taxpayer that enforced collection is on the table. The last rung is LT11 or Letter 1058, the Final Notice of Intent to Levy. This one comes with a legal right the earlier letters do not: thirty days to request a Collection Due Process hearing before the IRS can levy wages or bank accounts. After that window, the ladder ends in a levy (they take) or a lien (they secure their claim — see [[tax.lien]]).",
      },
      {
        kind: "prose",
        heading: "Why this is honest urgency",
        text: "You never have to invent pressure on these calls, because the ladder IS the pressure. A prospect holding a CP504 has a real clock running — not one you made up. That is the difference between fear-selling and [[strat.calm-urgency]]: you are not threatening them with what the IRS might do, you are reading them the schedule the IRS already published. The flip side of the same honesty: a CP14 is early. Someone on the first rung has time to do this right, and telling them so builds more trust than pretending the sky is falling.",
      },
      {
        kind: "prose",
        heading: "When a prospect mentions a letter",
        text: "A notice in the mail is the single most common reason these calls happen, so treat it as a gift. Before you name any options, get the facts: what notice is it (the number is printed top-right), what tax year, what amount, and is there a deadline on it. Was it certified mail? Certified usually means the serious end of the ladder. This is discovery gold — it tells you where they stand, and asking the questions shows them you actually know this system. If they name a state agency instead (FTB, a Department of Revenue), keep it separate — screen for whether there is ALSO a federal balance, because most files have both.",
      },
      {
        kind: "lines",
        heading: "Lines in the floor's voice",
        items: [
          "“Do you have the letter handy? There's a notice number in the top right corner — that tells us exactly where the IRS is in their process.”",
          "“A CP504 is the IRS formally telling you enforced collection is on the table. It's not a bluff — it's the step right before they can start taking.”",
          "“If that's an LT11, you have a legal window to respond before they can levy — and that window is exactly why timing matters here.”",
          "“The good news about a CP14 is you're early. You have time to handle this the right way instead of the panicked way.”",
        ],
      },
      {
        kind: "avoid",
        items: [
          "Don't guess what the notice means without asking which notice it is — a CP14 and an LT11 are different calls entirely.",
          "Don't manufacture urgency the letter doesn't carry. If they're on the first rung, say so; the trust you earn is worth more than the fake heat.",
          "Don't promise the letter can be “stopped” or the deadline moved. What we do is get represented and respond inside the process — never guarantee what the IRS will do.",
          "Don't assume federal. If they say “the state sent me something,” separate state from IRS and screen for both.",
        ],
      },
      {
        kind: "drill",
        prompt: "Prospect says: “I got some certified letter from the IRS last week but I haven't really read it.” — what's your move?",
        answer: "Certified mail is a signal the ladder is near the top. Ask them to grab it: “Certified usually means it's one of the serious ones. Can you grab it? There's a notice number in the top right — if it says LT11 or 1058, you have a legal response window, and that's exactly the kind of thing representation handles before it closes.” You've turned an unread envelope into discovery, honest urgency, and the pitch — without inventing anything.",
      },
    ],
    links: [
      "script.discovery",
      "script.expert",
      "strat.calm-urgency",
      "strat.cost-of-waiting",
      "tax.levy-garnishment",
      "tax.lien",
      "obj.no-urgency",
    ],
  },
  {
    id: "tax.levy-garnishment",
    part: "script",
    section: "tax",
    title: "Levy and garnishment: when the IRS is taking",
    aliases: [
      "wage garnishment",
      "bank levy",
      "they took my paycheck",
      "frozen bank account",
      "they're taking my wages",
      "levied",
      "garnished",
    ],
    lead: "A levy is the IRS actually taking — money out of a bank account, a slice out of every paycheck — and it keeps taking until the debt is paid or the levy is released. It is the most urgent situation you will hear on the floor, and the one where the promise-nothing rule matters most.",
    blocks: [
      {
        kind: "prose",
        heading: "What it actually is",
        text: "A lien secures; a levy takes. A bank levy freezes and then seizes funds sitting in the account on the day it lands. A wage levy — garnishment — goes to the employer, and a portion of every paycheck is sent to the IRS until the balance is paid or the levy is released. This is the end of the collections ladder ([[tax.collections-ladder]]): by the time someone is levied, the final notices came and went. The person on the phone is often already living it — short paychecks, a frozen account, rent in question. That's not a lead, that's a person in a fire.",
      },
      {
        kind: "prose",
        heading: "What representation actually does",
        text: "Once the firm is on file, the attorney's staff can contact the IRS directly, review the record, and request a levy release — typically by showing hardship or getting the taxpayer into a resolution posture. That is the honest verb: request. Releases happen, and getting representation filed fast is genuinely how it starts, but nobody on this floor can promise a release, a timeline, or a dollar back. The script's own framing is the right one: overcoming an active levy or garnishment is difficult, and we review all options immediately and transparently. Difficult-but-we-move-now is both true and compelling; “we'll stop it” is neither.",
      },
      {
        kind: "prose",
        heading: "How it lands in a pitch",
        text: "First, be a human being — one real acknowledgment, because someone whose check just got cut in half needs to hear that you registered it. Then confirm the enforcement fact: is money being taken right now, or did they get a notice that it's coming? Those are different fires. From there the pitch is the natural next sentence: the IRS will not talk strategy with an unrepresented taxpayer, so filing the POA is the first move in getting the taking reviewed. Urgency here is not a tactic; it is simply the truth of their situation, told calmly.",
      },
      {
        kind: "lines",
        heading: "Lines in the floor's voice",
        items: [
          "“That's rough — losing part of every check while you're trying to keep up. Let me ask you this: is money coming out right now, or did you get a notice that it's about to start?”",
          "“The IRS flagged your account for enforced collection. Once you're represented, the attorney's staff reviews the record and what adjustments may be available.”",
          "“I'll be straight with you — an active garnishment is difficult to overcome, and anyone who promises to stop it overnight is selling you something. What we do is get representation filed and review every option immediately.”",
          "“The garnishment doesn't pause while you think it over. Every pay cycle that passes is another check the IRS takes — that's why representation is the first move, not the last.”",
        ],
      },
      {
        kind: "avoid",
        items: [
          "Never promise the levy will be released, stopped, or paused — not even softened to “we usually get these released.” Say what we do: file representation and request a release.",
          "Don't skip the human beat. Jumping straight to the pitch when someone says “they emptied my account” reads as predatory.",
          "Don't confuse a levy with a lien on the call — if you mix them up, your expert frame dies. The lien secures; the levy takes.",
          "Don't dwell in the pain. One acknowledgment, then a concrete fact question that moves toward the fix.",
        ],
      },
      {
        kind: "example",
        weak: "“Oh wow, a garnishment? Yeah, we can get that stopped for you, that's what we do all day. Let's get you signed up and we'll shut it down.”",
        strong: "“I'm sorry — that's a hard thing to be dealing with every payday. Is it coming out of your check right now? … Okay. Here's the honest picture: an active garnishment is difficult to overcome, and the IRS won't discuss it with you strategically until someone represents you. That's why the POA is step one — it puts the attorney's staff in a position to review the levy and request a release based on your actual situation.”",
        note: "The weak version promises an outcome nobody controls — it's a compliance violation and it's exactly what the burned-before prospect has heard from the last firm. The strong version acknowledges, confirms the enforcement fact, tells the hard truth, and makes representation the obvious urgent first step.",
      },
      {
        kind: "compliance",
        text: "Representation can REQUEST a levy release; it cannot guarantee one. Never promise a stop, a release date, or returned funds. The offering is representation and a transparent review of options — say what we do, never what the IRS will give.",
      },
    ],
    links: [
      "tax.collections-ladder",
      "tax.lien",
      "tax.representation",
      "script.expert",
      "strat.calm-urgency",
      "strat.channel-relief",
      "strat.human-reassurance",
      "obj.hopeless",
    ],
  },
  {
    id: "tax.lien",
    part: "script",
    section: "tax",
    title: "The lien: a claim, not a seizure — and why your leads exist",
    aliases: [
      "tax lien",
      "lien on my house",
      "public record",
      "notice of federal tax lien",
      "lien vs levy",
      "filed a lien",
    ],
    lead: "A lien doesn't take anything today — it stakes the government's claim so it gets paid first if the taxpayer sells or liquidates. It's also filed in the public record, which is literally how outbound leads exist and how you answer “how did you get my number?”",
    blocks: [
      {
        kind: "prose",
        heading: "What a lien actually does",
        text: "A Notice of Federal Tax Lien is the IRS (or the state) publicly recording its claim against everything the taxpayer owns — house, car, business assets. It does not seize anything immediately. What it does is put the government first in line: sell the house, and the lien gets paid out of the proceeds before the seller sees a dime. It quietly clouds title, complicates refinancing, and follows the taxpayer until the debt is resolved or the lien is released. The one-line distinction to keep razor-sharp on calls: a lien SECURES, a levy TAKES ([[tax.levy-garnishment]]). Prospects mix these up constantly and often panic over the wrong one — clearing that up in one sentence is instant expert credibility.",
      },
      {
        kind: "prose",
        heading: "Public record — the honest answer to “how did you get my number?”",
        text: "Lien filings are public documents, recorded at the county or with the state. That public record is where some outbound lead lists come from. Today’s floor works mostly from online inquiries — and when that is the source, say that. But when a lead genuinely traces to a lien filing, the legitimacy question that opens the call has a completely honest answer: “Your name appeared in public tax records — often a state or federal filing or lien.” You are not dodging; you are explaining exactly how you knew to call — and the provenance you give must match where the lead actually came from. Said plainly, it converts the creepiest moment of a cold call into proof that the problem is real: the government published it.",
      },
      {
        kind: "prose",
        heading: "How it lands in a pitch",
        text: "A lien prospect usually isn't bleeding the way a levy prospect is, so the urgency is quieter but real: the lien sits on everything they own, and it is one rung below enforced collection on the ladder. The pitch angle is verification and standing: once represented, we verify the lien's accuracy and impact from the actual record — what it attaches to, what the balance behind it really is, and what the options are. And a lien on record means the IRS has already escalated once; the question worth asking out loud is what the next letter looks like if nothing changes.",
      },
      {
        kind: "lines",
        heading: "Lines in the floor's voice",
        items: [
          "Only when the lead source is a lien filing: “Your name appeared in public tax records — often a state or federal filing or lien. I'd like to confirm whether you still have an active matter that needs representation. Sound fair?”",
          "“A lien doesn't seize anything today — it secures the government's claim, so if you ever sell or refinance, they get paid first. It's a hold on your whole financial life more than a raid on it.”",
          "“Fair question — lien filings are public record, that's exactly how we knew to reach out. The IRS published it; we'd rather you hear from us than from their next letter.”",
          "“Once the file is open we verify the lien is even accurate — what it's attached to and what's really behind it. You'd be surprised how often the recorded number doesn't match the real balance.”",
        ],
      },
      {
        kind: "avoid",
        items: [
          "Don't inflate a lien into a levy to create heat. If you tell a lien prospect the IRS is “about to take everything,” you've traded your credibility for a scare that falls apart on inspection.",
          "Don't get cagey about the lead source. Hesitating on “how did you get my number?” reads as scam behavior when the truthful answer — public record — is your best legitimacy proof.",
          "Don't promise lien release, withdrawal, or subordination. Those are outcomes inside the IRS's process; what we do is verify the record and pursue the options it supports.",
        ],
      },
      {
        kind: "drill",
        prompt: "Prospect says: “There's a lien on my house — does that mean they're taking it?” — what's your move?",
        answer: "Calm the wrong fear, then point at the right one: “No — a lien doesn't seize anything. It secures their claim, so they're paid first if you ever sell or refinance. What it does tell us is the IRS has already escalated once, and the next rung on their ladder is the one that takes. That's what we'd want to get ahead of — once you're represented we pull the record and see exactly where you stand.” One sentence of relief, one sentence of honest urgency, then the foundation pitch.",
      },
    ],
    links: [
      "tax.levy-garnishment",
      "tax.collections-ladder",
      "script.intro",
      "strat.permission-legitimacy",
      "obj.how-got-number",
      "obj.scam-distrust",
    ],
  },
  {
    id: "tax.unfiled-sfr",
    part: "script",
    section: "tax",
    title: "Unfiled returns and the SFR: why the IRS's version costs more",
    aliases: [
      "haven't filed",
      "years behind",
      "substitute for return",
      "SFR",
      "back taxes",
      "didn't do my taxes",
      "missing returns",
      "wage and income transcript",
    ],
    lead: "When someone doesn't file, the IRS eventually files FOR them — a Substitute for Return built from raw income data with no deductions, no credits, and the worst filing status. The inflated balance that results is often the debt they're calling about, and filing correctly is the gate every resolution sits behind.",
    blocks: [
      {
        kind: "prose",
        heading: "What an SFR is and why it inflates",
        text: "The IRS already knows most of what a person earned — employers and payers report W-2s and 1099s straight to them. When returns go unfiled long enough, the IRS uses that data to file a Substitute for Return: all the income, none of the taxpayer's side of the story. No deductions, no dependents, no business expenses, usually single filing status. A self-employed prospect gets hit hardest — an SFR taxes their gross 1099 income as if every dollar were profit. So the balance an unfiled prospect is staring at is frequently not their real number; it's the worst-case number the IRS was forced to assume. That's not spin — it's the honest mechanics, and it reframes “I owe $80,000” into “the IRS guessed $80,000 because you never told them otherwise.”",
      },
      {
        kind: "prose",
        heading: "Compliance gates everything",
        text: "Here is the rule that shapes every one of these calls: the IRS will not entertain ANY resolution — installment agreement, offer, hardship status — while returns are missing. Filing compliance is the toll gate in front of all of it ([[tax.resolution-options]]). This is why “I'll just wait and deal with it later” doesn't work and why the unfiled prospect can't skip to negotiating: nobody can negotiate a balance built on missing returns. It also means cleanup is never wasted work — it's the mandatory first step of literally every path forward.",
      },
      {
        kind: "prose",
        heading: "How representation attacks it",
        text: "Once the 8821 and 2848 are on file, the first move is usually pulling the wage & income transcripts — the IRS's own record of every W-2, 1099, and payer report for each missing year. That's what lets the returns get filed correctly instead of from a shoebox and a guess: real income data, plus the deductions and status the SFR ignored. A correctly filed return can replace the SFR's assessment, and the balance moves to what it actually should be. In discovery, find the shape of it first — which years are missing, and what kind of income (W-2 versus 1099 changes everything). Frame cleanup as the first step before anyone guesses at resolution.",
      },
      {
        kind: "lines",
        heading: "Lines in the floor's voice",
        items: [
          "“When you don't file, the IRS files for you — and their version gives you no deductions, no write-offs, nothing. It's the worst-case math, which is why that balance is probably inflated.”",
          "“Which years are we missing, and was that W-2 work or 1099? That changes the whole picture.”",
          "“Here's the thing most people don't know: the IRS won't discuss any resolution — payment plan, anything — while returns are missing. Filing correctly isn't a side task, it's the gate everything else sits behind.”",
          "“Once you're represented we pull your wage and income transcripts — the IRS's own record of what was reported for you — and get those years filed right. Then we're negotiating your real number, not their guess.”",
        ],
      },
      {
        kind: "avoid",
        items: [
          "Don't promise the balance will drop. Correct filing often reduces an SFR-based assessment, but “often” is not “will” — say the SFR is built without deductions and correct filing shows the real number.",
          "Don't let shame stall discovery. Years of unfiled returns embarrass people; normalize it (“you're not the first, this is most of what we see”) and move to the fact questions.",
          "Don't quote a filing-only price or treat this as a tax-prep sale — the product is representation plus compliance, and [[obj.just-file-returns]] has its own handling.",
          "Don't guess at resolution options before the missing years are even identified. Cleanup first; anything else is speculation.",
        ],
      },
      {
        kind: "drill",
        prompt: "Prospect says: “I haven't filed in six years and now they say I owe $90,000. There's no way I owe that.” — what's your move?",
        answer: "Agree with their instinct and explain why it might be right: “You might not — and here's why. When you don't file, the IRS files substitute returns for you, using just the raw income reported and zero deductions. It's worst-case math. The only way to know your real number is to pull your wage and income transcripts and file those years correctly — and until they're filed, the IRS won't discuss any kind of resolution anyway. So that's step one either way.” Their disbelief becomes your pitch.",
      },
    ],
    links: [
      "tax.resolution-options",
      "tax.representation",
      "script.discovery",
      "script.expert",
      "strat.shame-reduction",
      "obj.just-file-returns",
      "obj.dont-owe",
    ],
  },
  {
    id: "tax.resolution-options",
    part: "script",
    section: "tax",
    title: "Resolution options: IA, OIC, CNC, penalty abatement — general answers only",
    aliases: [
      "payment plan",
      "installment agreement",
      "offer in compromise",
      "settle for less",
      "pennies on the dollar",
      "fresh start",
      "currently not collectible",
      "hardship status",
      "penalty abatement",
    ],
    lead: "Know the four main resolution paths cold — and then answer generally anyway. The product is representation and compliance, not a pre-picked outcome, because nobody can honestly name the right option before seeing the file.",
    blocks: [
      {
        kind: "prose",
        heading: "The four paths",
        text: "Installment Agreement: a monthly payment plan with the IRS — the most common resolution, structured around what the taxpayer can actually pay. Offer in Compromise: settling the debt for less than the full balance — real, but rare and strict. The IRS accepts an OIC only when the numbers show it genuinely cannot collect the full amount from income and assets within the time it has; it is a financial-disclosure grind, not a negotiation trick. Currently Not Collectible: a hardship pause — the IRS marks the account uncollectible and collection stops while the hardship holds; the debt doesn't vanish, but the taking does. Penalty Abatement: removing penalties (which can be a big slice of the balance) for reasonable cause or under first-time abatement. Every one of them sits behind the same gate: filing compliance ([[tax.unfiled-sfr]]) — no missing returns, or the IRS won't discuss any of it.",
      },
      {
        kind: "prose",
        heading: "The OIC trap — and the honest framing",
        text: "The prospect has heard the radio ads: “settle for pennies on the dollar.” That promise is the signature move of the firms that burned the people you call, and it's the fastest way to sound like them. The honest framing sells better anyway: yes, offers exist; no, most people don't qualify; the ONLY way to know is a real financial analysis against the actual transcripts. A firm that says “you qualify” before seeing the file is guessing on commission. You differentiate exactly the way the script does — a lot of companies rush to big promises, we take the responsible path: represent, verify, then outline real options based on facts.",
      },
      {
        kind: "prose",
        heading: "Why you answer generally",
        text: "The rule of this entire section: keep tax answers general, because the value is getting represented and seeing the real file. If a prospect asks “which one would I get?”, the true answer is that anyone who tells them on a first phone call is making it up — the right option falls out of what's owed, what's filed, and what the IRS has on record (the three factors). This is not dodging; it is the reason representation exists. You demonstrate expertise by knowing all four paths fluently and by refusing to fake certainty. Knowledge is credibility; a premature verdict is a lie with your name on it.",
      },
      {
        kind: "lines",
        heading: "Lines in the floor's voice",
        items: [
          "“There are a few real paths — a payment plan, an offer in compromise, hardship status, penalty removal. Which one fits you isn't something anyone can honestly tell you until we see your actual transcripts.”",
          "“Offers in compromise are real, but I'll be straight with you: they're rare and the IRS is strict. Anyone who promises you one before pulling your file is guessing — and you've probably talked to those companies already.”",
          "“Penalties can be a huge slice of your balance, and in some cases they can be removed — first-time abatement or reasonable cause. That's exactly the kind of thing we check once we're inside the file.”",
          "“Every one of those options has the same first requirement: your returns have to be filed. That's why compliance is step one no matter which road this ends up on.”",
        ],
      },
      {
        kind: "avoid",
        items: [
          "Never tell a prospect they qualify for an OIC, will settle for less, or will save a specific dollar amount. That is the burned-them-before pitch, and it's a compliance line you do not cross.",
          "Don't pick their resolution on the call — not even hedged as “you'd probably get.” The three factors decide, and you haven't seen them.",
          "Don't dump all four options as a lecture. Name the landscape in a sentence or two, then bring it back to why the file decides.",
          "Don't disparage the options either — “nobody ever gets an offer” is as dishonest as promising one. Rare and strict is the truth; say it that way.",
        ],
      },
      {
        kind: "example",
        weak: "“Honestly, with a balance like yours, you're a perfect candidate for the Fresh Start program. We settle these for pennies on the dollar all the time — I'd bet we get you down to a fraction of that.”",
        strong: "“There are a few real paths — payment plan, offer in compromise, hardship status, penalty removal. I could pretend to know which one you'd land on, but that would make me the fourth company to guess at your case over the phone. The right answer comes out of your actual transcripts — what's owed, what's filed, what the IRS has done. That's what representation opens up.”",
        note: "The weak version promises an outcome — a compliance breach and the exact pitch the prospect has learned to distrust. The strong version shows full command of the options, names the industry's bad habit, and turns honesty itself into the differentiator.",
      },
      {
        kind: "compliance",
        text: "Never promise a settlement, an OIC, a dollar reduction, or a resolution timeline. Describe the options generally, and always land on: the file decides, and representation is how we see the file. What we sell is representation plus compliance — never a guaranteed outcome.",
      },
    ],
    links: [
      "tax.unfiled-sfr",
      "tax.representation",
      "tax.csed",
      "script.expert",
      "script.pitch",
      "strat.confident-value-frame",
      "obj.guarantee-seeking",
      "obj.oic-myself",
      "obj.success-rate",
    ],
  },
  {
    id: "tax.representation",
    part: "script",
    section: "tax",
    title: "Representation: Forms 2848, 8821, and the state POA",
    aliases: [
      "power of attorney",
      "POA",
      "2848",
      "8821",
      "tax information authorization",
      "talk to the IRS for me",
      "on my behalf",
      "pull transcripts",
    ],
    lead: "Representation is the product. Three authorizations — IRS Form 2848, Form 8821, and the state POA — put licensed professionals between the taxpayer and the IRS and open the full file. It is a foundation, not a fix, and knowing exactly what each form does is what makes the pitch land.",
    blocks: [
      {
        kind: "prose",
        heading: "What the three forms actually do",
        text: "Form 2848 is a limited Power of Attorney: it authorizes the attorney's staff to speak directly with the IRS and receive case information — the IRS now deals with professionals instead of a scared taxpayer on hold. Form 8821 is the Tax Information Authorization: it opens the master file, letting us pull transcripts and review every balance, filing, and notice on record. The state POA does the same at the state level, because most files have a state side too. Together they answer the problem the three-factors frame names: every case comes down to what's owed, what's filed, and what the IRS has already done — and until someone represents you, the IRS makes it hard to see the full details.",
      },
      {
        kind: "prose",
        heading: "A foundation, not a fix",
        text: "The script's own framing is the one to keep: these forms don't change your balance; they open the door so we can see the facts and communicate lawfully. Never oversell the POA as the thing that solves the debt — it is the thing that makes solving it possible. That honesty is also the setup for healthy urgency: tax-debt work is a marathon, not a sprint, and representation is the starting line. If the prospect has had active IRS communication, the sooner representation is filed, the sooner the legal team engages — and nothing moves forward without it. Once filed, the file gets a full compliance check and review by the attorney’s staff as the record comes back; that is the concrete thing they are buying today.",
      },
      {
        kind: "prose",
        heading: "The CPA distinction",
        text: "The most common capability objection on this floor — “I already have a CPA” — dissolves on one distinction: filing returns is not collection representation. A CPA who prepares taxes is doing compliance work; active collection representation means someone holds a POA, stands between the taxpayer and IRS collections, negotiates within the process, and answers the enforcement letters. Ask the diagnostic question: has your CPA filed a power of attorney with the IRS? Is he the one dealing with these collection notices? Almost always the answer is no — and now the prospect sees the gap themselves instead of hearing you knock their guy. Same logic for [[obj.working-with-irs]]: talking to the IRS yourself, unrepresented, is exactly the situation representation ends.",
      },
      {
        kind: "lines",
        heading: "Lines in the floor's voice",
        items: [
          "“The first step toward resolving any tax matter is getting you formally represented — three authorizations: IRS Form 2848, Form 8821, and the state POA if applicable.”",
          "“The 2848 means the attorney's staff speak directly with the IRS for you. The 8821 opens your master file — every balance, every filing, every notice, so we're working from facts instead of guesses.”",
          "“These forms don't change your balance — I want to be straight about that. They open the door so we can see the facts and communicate lawfully. It's the foundation, not the fix.”",
          "“Quick question — has your CPA filed a power of attorney with the IRS? Is he the one answering these collection letters? … Right. That's the difference. He does your returns; nobody's standing in front of collections for you.”",
        ],
      },
      {
        kind: "avoid",
        items: [
          "Don't sell the POA as the resolution. “Once we file this, the problem's handled” overpromises the foundation into a fix — and sets up the exact disappointment that creates burned-before prospects.",
          "Don't drown them in form numbers. Name the three, give each a one-line plain-English job, and move on — educate without jargon.",
          "Don't bash the CPA. The move is the diagnostic question that reveals the gap, not “your guy doesn't know collections.”",
          "Don't skip the state POA when the file has a state side — half the pain often lives there.",
        ],
      },
      {
        kind: "drill",
        prompt: "Prospect says: “Why would I pay you just to fill out some forms? I can talk to the IRS myself.” — what's your move?",
        answer: "Reframe what the forms buy: “The forms are the door, not the service. What you're actually getting is the attorney's staff speaking to the IRS for you, your entire master file pulled and reviewed — every balance, filing, and notice — and a compliance check that tells you exactly where you stand. You can absolutely call the IRS yourself; what you'll get is whoever answers, reading you one screen. Representation is the difference between asking the IRS what's happening and having your own team see the whole record.”",
      },
    ],
    links: [
      "script.pitch",
      "script.expert",
      "tax.resolution-options",
      "tax.levy-garnishment",
      "strat.confident-value-frame",
      "strat.expert-specificity",
      "obj.already-have-cpa",
      "obj.working-with-irs",
      "obj.diy-self-rep",
    ],
  },
  {
    id: "tax.payroll-941-tfrp",
    part: "script",
    section: "tax",
    title: "Payroll tax, 941s, and the Trust Fund Recovery Penalty",
    aliases: [
      "payroll taxes",
      "941",
      "940",
      "trust fund",
      "TFRP",
      "business owes taxes",
      "employment tax",
      "responsible person",
      "quarterlies",
    ],
    lead: "Payroll debt is the IRS's angriest category: withheld employee money that never got sent in is treated as theft from the government, and the Trust Fund Recovery Penalty can pin it on the owner personally — even through a closed business or a bankruptcy. These calls carry real urgency and a very personal fear.",
    blocks: [
      {
        kind: "prose",
        heading: "Why payroll debt is different",
        text: "When a business withholds taxes from employee paychecks, that money is never the business's — it is held in trust for the government. A 941 balance means withheld trust money didn't get sent in, and the IRS treats that as the most serious kind of tax debt it collects. It escalates faster, revenue officers get assigned sooner, and the tone of enforcement is harsher than anything an individual with a 1040 balance experiences. The prospect on a payroll call is usually a business owner who used the withholding to make rent on the shop or cover a brutal quarter — a survival decision the IRS reads as taking its money.",
      },
      {
        kind: "prose",
        heading: "The TFRP: why it's personal",
        text: "The Trust Fund Recovery Penalty is the mechanism that makes business debt personal. The IRS can assess the trust-fund portion of unpaid payroll taxes directly against any “responsible person” — an owner, an officer, sometimes a bookkeeper or anyone with signature authority who chose to pay other bills instead. The corporate shield does not stop it, closing the business does not erase it, and it is generally not dischargeable in bankruptcy. If a prospect mentions IRS letters using “trust fund” or “responsible person” language, or an interview request (Form 4180), the personal-assessment machinery is already moving — that is top-of-the-ladder urgency, no exaggeration required.",
      },
      {
        kind: "prose",
        heading: "How it runs in discovery and the pitch",
        text: "The house guidance for these calls: separate business and personal exposure — ask which quarters and years are behind, whether the business is still operating, and whether trust-fund or responsible-person language has appeared in anything they've received. Those three facts frame the whole case. The script's expert line carries the pitch: business and payroll taxes blend business and personal liability, and representation separates what's actually yours. That word — separates — is the promise-safe value: we don't claim to make the debt vanish; we get inside the file, split what belongs to the entity from what's being aimed at the person, and respond inside the process before the personal assessment lands.",
      },
      {
        kind: "lines",
        heading: "Lines in the floor's voice",
        items: [
          "“Payroll debt is the one the IRS takes most personally — that withholding was your employees' money in trust, so they move faster and harder on it than anything else.”",
          "“Which quarters are behind, and is the business still operating? Those two answers change everything about how this gets handled.”",
          "“Have any of the letters mentioned ‘trust fund' or ‘responsible person'? That's the language they use right before they move the debt from the business onto you personally.”",
          "“Business and payroll taxes blend business and personal liability. Once you're represented, we separate what's actually yours — that's the whole fight on these cases.”",
        ],
      },
      {
        kind: "avoid",
        items: [
          "Don't treat a payroll case like a 1040 case with a bigger number — the enforcement speed and the personal-assessment threat make it a different animal, and the prospect can tell if you don't know that.",
          "Don't promise the TFRP can be avoided, removed, or that the owner “won't be personally liable.” We investigate responsibility, separate exposure, and respond inside the process — that's the honest verb set.",
          "Don't moralize about the withholding. They know. Most used it to keep people employed — shame stalls the call; facts move it.",
          "Don't skip the operating-status question. An open business with ongoing payroll is a compounding problem; a closed one is a personal-assessment problem. Different cases.",
        ],
      },
      {
        kind: "drill",
        prompt: "Prospect says: “The business owes the 941s, not me — and honestly the business is about done anyway. Can't I just close it and walk away?” — what's your move?",
        answer: "This is the most dangerous belief on a payroll call — correct it without gloating: “I wish it worked that way. The trust-fund portion of payroll debt is the one thing the IRS can move from the business onto you personally — it's called the Trust Fund Recovery Penalty, and closing the doors doesn't stop it. If any letter has said ‘responsible person,' that process may already be moving. That's exactly why representation matters now: we get in the file and separate what's the entity's from what they're trying to make yours, before that assessment lands.”",
      },
      {
        kind: "compliance",
        text: "Never promise the owner will avoid personal liability, that the TFRP won't be assessed, or that closing the business ends the exposure. What we do: separate business from personal liability, verify the record, and respond within the process.",
      },
    ],
    links: [
      "tax.representation",
      "tax.collections-ladder",
      "script.discovery",
      "script.expert",
      "strat.calm-urgency",
      "strat.expert-specificity",
    ],
  },
  {
    id: "tax.csed",
    part: "script",
    section: "tax",
    title: "The CSED: the 10-year clock, what pauses it, and the transcript answer",
    aliases: [
      "statute of limitations",
      "isn't this expired",
      "debt is too old",
      "10 year rule",
      "collection statute",
      "CSED",
      "debt from years ago",
    ],
    lead: "The IRS generally gets ten years from assessment to collect — the Collection Statute Expiration Date. But the clock pauses for more events than prospects realize, so the honest answer to “isn't this expired?” is never yes or no from the phone. It's: the transcript knows, let's pull it.",
    blocks: [
      {
        kind: "prose",
        heading: "How the clock actually runs",
        text: "The CSED is real law: roughly ten years from the date each balance was ASSESSED — not from the tax year, and not from when the return was due. That distinction alone reshuffles most prospects' math. A 2016 return filed late in 2019 was assessed in 2019; an audit that added tax in 2021 started a fresh ten-year clock on that piece in 2021. One taxpayer can have several balances, each with its own CSED. So “this debt is from years ago” tells you almost nothing about whether it's expired — the assessment dates do, and those live on the transcript.",
      },
      {
        kind: "prose",
        heading: "What tolls the clock",
        text: "The clock also stops running — “tolls” — during events that legally block the IRS from collecting. The big ones: an Offer in Compromise pending (the whole time it's under review, plus a buffer), a Collection Due Process hearing after an LT11 or Letter 1058, bankruptcy (the automatic stay, plus six months), and extended time living outside the country. Requesting an installment agreement or innocent spouse relief pauses it too. Here's the twist worth knowing cold: some of the ways people “fought” their debt are exactly what kept it alive. A prospect who filed an OIC through some firm in 2019 and spent a year in review added that year to the IRS's collection window. The taxpayer's memory of the timeline and the legal timeline are almost never the same document.",
      },
      {
        kind: "prose",
        heading: "The honest answer — and why it's also the pitch",
        text: "When a prospect says “this is from 2014 — isn't it expired?”, the two wrong answers are “no it's not” and “yes it is.” Both are guesses. The strong handling per the house playbook: explain that the CSED exists (ten years from assessment), name the events that toll it, and offer to verify the actual CSED via transcript. This objection is secretly a gift, because the answer IS the product: the transcript shows the assessment date and every tolling event, and pulling it takes representation ([[tax.representation]]). If the debt truly is expired or about to expire, they deserve to know that too — which is what makes the offer credible. You're not arguing them out of hope; you're offering to check the one document that settles it.",
      },
      {
        kind: "lines",
        heading: "Lines in the floor's voice",
        items: [
          "“You're thinking of the right rule — the IRS does have ten years to collect. But it runs from the assessment date, not the tax year, and it pauses for things like a pending offer, a hearing, or a bankruptcy. So the calendar answer and the legal answer are usually different.”",
          "“Honestly? I can't tell you from here whether it's expired — and neither can anyone else on a phone call. Your transcript shows the exact assessment date and every event that paused the clock. That's a five-minute read once we can pull it.”",
          "“Here's the part that surprises people: if you ever filed an offer or requested a hearing, the clock stopped while that was pending. Sometimes the thing someone did to fight the debt is what kept it alive.”",
          "“If it IS expired, you deserve to know that too — the transcript settles it either way. Let's find out what's actually on the record instead of guessing.”",
        ],
      },
      {
        kind: "avoid",
        items: [
          "Never say “yes it's expired” or “no it isn't” without the transcript — either guess can be wrong, and one of them talks you out of a sale that was legitimate.",
          "Don't dodge the question or act like the CSED is a myth — the prospect heard something true. Confirm the rule exists; expertise here is the trust move.",
          "Don't promise the debt will fall off on a date, or use an approaching CSED as a promise (“just wait it out”) — the IRS accelerates enforcement as clocks near expiration, and tolling events you can't see may have moved the date anyway.",
          "Don't compute a CSED for them from what they remember. Their timeline is missing the tolling events by definition.",
        ],
      },
      {
        kind: "example",
        weak: "“No, that's a myth — tax debt never expires. The IRS will chase you forever, so you might as well deal with it now.”",
        strong: "“You're actually right that there's a clock — ten years from when each balance was assessed. But it pauses for things like a pending offer, a hearing after a final notice, or a bankruptcy, so the real expiration date is almost never what the calendar suggests. Your transcript shows the exact date. If it's expired, you deserve to know that — and if it's not, you'll want to know how much clock is left. Either way, that's the first thing we check once you're represented.”",
        note: "The weak version is flatly false and dies the moment the prospect googles it — credibility gone. The strong version validates what they heard, teaches the tolling twist they didn't know, and makes the transcript pull — the product — the only honest way to settle it.",
      },
      {
        kind: "compliance",
        text: "Never assert a debt is or isn't expired, and never predict the date it will be. The CSED is verified from the transcript — the honest offer is to check the record, whatever it shows.",
      },
    ],
    links: [
      "obj.debt-expired-csed",
      "tax.representation",
      "tax.collections-ladder",
      "tax.resolution-options",
      "script.expert",
      "strat.expert-specificity",
      "strat.earn-trust-with-proof",
    ],
  },
];
